CREATE TABLE IF NOT EXISTS sol_cloud_sync_state (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  authority_id uuid NOT NULL DEFAULT gen_random_uuid(),
  bootstrapped_at timestamptz,
  last_pushed_seq bigint NOT NULL DEFAULT 0,
  last_sync_at timestamptz,
  last_sync_error text
);

INSERT INTO sol_cloud_sync_state(singleton)
VALUES (true)
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS sol_sync_changes (
  seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name text NOT NULL,
  operation char(1) NOT NULL CHECK (operation IN ('I', 'U', 'D')),
  primary_key jsonb NOT NULL,
  row_data jsonb,
  changed_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sol_sync_changes_pending_idx
  ON sol_sync_changes(seq);

CREATE OR REPLACE FUNCTION sol_sync_primary_key(
  relation_oid oid,
  row_data jsonb
)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $$
  SELECT COALESCE(jsonb_object_agg(attribute.attname, row_data -> attribute.attname), '{}'::jsonb)
  FROM pg_index index_info
  JOIN pg_attribute attribute
    ON attribute.attrelid = index_info.indrelid
   AND attribute.attnum = ANY(index_info.indkey)
  WHERE index_info.indrelid = relation_oid
    AND index_info.indisprimary;
$$;

CREATE OR REPLACE FUNCTION sol_capture_sync_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  captured_row jsonb;
  captured_key jsonb;
BEGIN
  IF current_setting('sol.sync_apply', true) = '1' THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  captured_row := CASE
    WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD)
    ELSE to_jsonb(NEW)
  END;
  captured_key := sol_sync_primary_key(TG_RELID, captured_row);

  IF captured_key = '{}'::jsonb THEN
    IF TG_OP = 'DELETE' THEN
      RETURN OLD;
    END IF;
    RETURN NEW;
  END IF;

  INSERT INTO sol_sync_changes(table_name, operation, primary_key, row_data)
  VALUES (
    TG_TABLE_NAME,
    substring(TG_OP, 1, 1),
    captured_key,
    CASE WHEN TG_OP = 'DELETE' THEN NULL ELSE captured_row END
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION sol_install_sync_triggers()
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  relation record;
  installed integer := 0;
BEGIN
  FOR relation IN
    SELECT class.oid, class.relname
    FROM pg_class class
    JOIN pg_namespace namespace ON namespace.oid = class.relnamespace
    WHERE namespace.nspname = 'public'
      AND class.relkind IN ('r', 'p')
      AND class.relname NOT IN (
        'schema_migrations',
        'sol_cloud_sync_state',
        'sol_sync_changes'
      )
      AND EXISTS (
        SELECT 1
        FROM pg_index index_info
        WHERE index_info.indrelid = class.oid
          AND index_info.indisprimary
      )
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS sol_cloud_sync_capture ON public.%I',
      relation.relname
    );
    EXECUTE format(
      'CREATE TRIGGER sol_cloud_sync_capture AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION sol_capture_sync_change()',
      relation.relname
    );
    installed := installed + 1;
  END LOOP;

  RETURN installed;
END;
$$;

SELECT sol_install_sync_triggers();
