export function renderCalendarPage(): string {
  return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SOL · Calendar</title>
<style>
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText}main{width:min(980px,calc(100% - 32px));margin:auto;padding:46px 0 80px}a{color:inherit}.top,.row{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.brand{font-size:14px;font-weight:850;letter-spacing:.18em;opacity:.7}nav{display:flex;gap:14px;font-size:14px}h1{font-size:clamp(34px,6vw,58px);letter-spacing:-.04em;margin:12px 0 8px}h2{margin:0 0 7px;font-size:21px}h3{font-size:16px;margin:22px 0 8px}p{line-height:1.55;opacity:.8}.card{border:1px solid color-mix(in srgb,CanvasText 16%,transparent);border-radius:20px;padding:22px;margin-top:20px}.pill{border:1px solid color-mix(in srgb,CanvasText 18%,transparent);border-radius:999px;padding:6px 10px;font-size:12px}.muted{opacity:.62}.error{color:#d33}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:6px;font-size:13px;font-weight:700}input,select{padding:10px 12px;border-radius:11px;border:1px solid color-mix(in srgb,CanvasText 20%,transparent);background:Canvas;color:CanvasText;font:inherit}button{border:0;border-radius:999px;padding:10px 14px;font:inherit;font-weight:750;cursor:pointer;background:CanvasText;color:Canvas}.secondary{background:transparent;color:CanvasText;border:1px solid color-mix(in srgb,CanvasText 20%,transparent)}.danger{background:transparent;color:#d33;border:1px solid #d336}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.cal{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:center;padding:10px 0;border-top:1px solid color-mix(in srgb,CanvasText 10%,transparent)}.cal:first-child{border-top:0}.event{padding:10px 0;border-top:1px solid color-mix(in srgb,CanvasText 9%,transparent)}@media(max-width:680px){.grid{grid-template-columns:1fr}.cal{grid-template-columns:1fr 1fr}.cal>div:first-child{grid-column:1/-1}}
</style></head><body><main>
<div class="top"><div class="brand">SOL · CALENDAR</div><nav><a href="/">Inicio</a><a href="/whatsapp">WhatsApp</a><a href="/executive">Día a día</a><a href="/ai">AI</a></nav></div>
<h1>Agenda familiar.</h1><p>Cada miembro puede conectar sus propias cuentas. Un calendario puede leerse sin ser destino de escritura; SOL sólo escribe después de una aprobación explícita.</p>
<section id="app" class="card"><p class="muted">Cargando…</p></section></main>
<script>
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function api(path,options={}){const response=await fetch(path,{cache:'no-store',...options});let body={};try{body=await response.json()}catch{}return{response,body}}
async function calendarsFor(account){const r=await api('/v1/calendar/accounts/'+encodeURIComponent(account.id)+'/calendars');return r.response.ok?r.body.calendars:[]}
async function renderAccount(account){const calendars=account.canRead?await calendarsFor(account):[];return '<article class="card"><div class="row"><div><h2>'+esc(account.label)+'</h2><div class="muted">'+esc(account.ownerMemberId?'personal':'familiar')+(account.googleEmail?' · '+esc(account.googleEmail):'')+'</div></div><span class="pill">'+esc(account.status)+'</span></div>'+(account.canManage?'<div class="actions"><button data-connect="'+esc(account.id)+'">'+(account.status==='connected'?'Reconectar Google':'Conectar Google')+'</button>'+(account.status==='connected'?'<button class="secondary" data-sync="'+esc(account.id)+'">Sincronizar</button><button class="danger" data-disconnect="'+esc(account.id)+'">Desconectar</button>':'')+'</div>':'')+(calendars.length?'<h3>Calendarios</h3><div>'+calendars.map(c=>'<div class="cal"><div><strong>'+esc(c.summary)+'</strong><div class="muted">'+esc(c.accessRole)+(c.primary?' · principal':'')+'</div></div><label><input type="checkbox" data-cal-sync="'+esc(c.id)+'" data-account="'+esc(account.id)+'" '+(c.selectedForSync?'checked':'')+'> Leer</label><label><input type="radio" name="write-'+esc(account.id)+'" data-cal-write="'+esc(c.id)+'" data-account="'+esc(account.id)+'" '+(c.selectedForWrite?'checked':'')+' '+(!['writer','writerWithoutPrivateAccess','owner'].includes(c.accessRole)?'disabled':'')+'> Escribir</label></div>').join('')+'</div>':'')+'</article>'}
async function load(){const [me,status,accountsR]=await Promise.all([api('/v1/auth/me'),api('/v1/calendar/status'),api('/v1/calendar/accounts')]);if(!me.response.ok){app.innerHTML='<h2>Necesitás iniciar sesión</h2><p><a href="/">Volver</a></p>';return}if(!status.body.configured){app.innerHTML='<h2>Falta configurar Google OAuth</h2><p>Agregá SOL_GOOGLE_CLIENT_ID y SOL_GOOGLE_CLIENT_SECRET al .env, y registrá el callback <code>http://127.0.0.1:3000/v1/google/callback</code> en Google Cloud.</p>';return}const accounts=accountsR.body.accounts||[];const member=me.body.member;const canAdd=!['child','guest'].includes(member.role);const canShared=['owner','adult'].includes(member.role);const cards=[];for(const a of accounts)cards.push(await renderAccount(a));app.innerHTML='<div class="row"><div><h2>Cuentas Google Calendar</h2><div class="muted">'+esc(member.displayName)+' · '+esc(member.role)+'</div></div><span class="pill">'+accounts.length+' cuenta(s)</span></div>'+(canAdd?'<form id="new" class="card"><div class="grid"><label>Nombre<input name="label" value="Google Calendar personal" required></label>'+(canShared?'<label>Propiedad<select name="shared"><option value="false">Personal</option><option value="true">Familiar</option></select></label>':'')+'</div><button>Conectar nueva cuenta</button><span id="new-status" class="muted"></span></form>':'')+cards.join('')+'<article class="card"><div class="row"><div><h2>Próximos 7 días</h2><div class="muted">Vista combinada de calendarios autorizados</div></div><button class="secondary" id="load-events">Cargar</button></div><div id="events"></div></article>';bind();}
function bind(){const form=document.getElementById('new');if(form)form.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form).entries());const s=document.getElementById('new-status');s.textContent='Iniciando OAuth…';const r=await api('/v1/calendar/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:d.label,shared:d.shared==='true'})});if(!r.response.ok){s.textContent=r.body.error||'Error';return}location.href=r.body.login.authorizationUrl});document.querySelectorAll('[data-connect]').forEach(b=>b.addEventListener('click',async()=>{const r=await api('/v1/calendar/accounts/'+b.dataset.connect+'/connect',{method:'POST'});if(r.response.ok)location.href=r.body.login.authorizationUrl;else alert(r.body.error||'Error')}));document.querySelectorAll('[data-sync]').forEach(b=>b.addEventListener('click',async()=>{b.disabled=true;const r=await api('/v1/calendar/accounts/'+b.dataset.sync+'/sync',{method:'POST'});if(!r.response.ok)alert(r.body.error||'Error');await load()}));document.querySelectorAll('[data-disconnect]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('¿Desconectar esta cuenta de Google Calendar?'))return;await api('/v1/calendar/accounts/'+b.dataset.disconnect+'/disconnect',{method:'POST'});await load()}));document.querySelectorAll('[data-cal-sync]').forEach(c=>c.addEventListener('change',()=>patchCal(c.dataset.calSync,c.dataset.account,{selectedForSync:c.checked})));document.querySelectorAll('[data-cal-write]').forEach(c=>c.addEventListener('change',()=>{if(c.checked)patchCal(c.dataset.calWrite,c.dataset.account,{selectedForWrite:true})}));const loadEvents=document.getElementById('load-events');if(loadEvents)loadEvents.addEventListener('click',async()=>{const from=new Date(),to=new Date(Date.now()+7*86400000);const r=await api('/v1/calendar/upcoming?from='+encodeURIComponent(from.toISOString())+'&to='+encodeURIComponent(to.toISOString()));const target=document.getElementById('events');if(!r.response.ok){target.innerHTML='<p class="error">'+esc(r.body.error)+'</p>';return}target.innerHTML=(r.body.events||[]).map(e=>'<div class="event"><strong>'+esc(e.title)+'</strong><div class="muted">'+esc(e.calendarName)+' · '+esc(e.start.dateTime||e.start.date||'')+'</div></div>').join('')||'<p class="muted">Sin eventos.</p>'})}
async function patchCal(id,account,payload){const r=await api('/v1/calendar/calendars/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({sourceAccountId:account,...payload})});if(!r.response.ok)alert(r.body.error||'No se pudo actualizar');else await load()}
load();
</script></body></html>`;
}
