export function renderExecutivePage(): string {
  return `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>SOL · Día a día</title>
<style>
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText}main{width:min(960px,calc(100% - 32px));margin:auto;padding:46px 0 80px}a{color:inherit}.top,.row{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap}.brand{font-size:14px;font-weight:850;letter-spacing:.18em;opacity:.7}nav{display:flex;gap:14px;font-size:14px}h1{font-size:clamp(34px,6vw,58px);letter-spacing:-.04em;margin:12px 0 8px}h2{margin:0 0 7px;font-size:21px}p{line-height:1.55;opacity:.8}.card{border:1px solid color-mix(in srgb,CanvasText 16%,transparent);border-radius:20px;padding:22px;margin-top:20px}.proposal{padding:14px 0;border-top:1px solid color-mix(in srgb,CanvasText 10%,transparent)}.proposal:first-child{border-top:0}.pill{display:inline-flex;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);border-radius:999px;padding:5px 9px;font-size:12px}.muted{opacity:.62}.error{color:#d33}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}button{border:0;border-radius:999px;padding:9px 13px;font:inherit;font-weight:750;cursor:pointer;background:CanvasText;color:Canvas}.secondary{background:transparent;color:CanvasText;border:1px solid color-mix(in srgb,CanvasText 20%,transparent)}pre{white-space:pre-wrap;font:inherit;line-height:1.55;margin:12px 0 0}.brief-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.stat{border:1px solid color-mix(in srgb,CanvasText 12%,transparent);border-radius:14px;padding:14px}.stat b{display:block;font-size:24px}@media(max-width:680px){.brief-grid{grid-template-columns:1fr}}
</style></head><body><main>
<div class="top"><div class="brand">SOL · DÍA A DÍA</div><nav><a href="/">Inicio</a><a href="/calendar">Calendar</a><a href="/whatsapp">WhatsApp</a><a href="/ai">AI</a></nav></div>
<h1>Qué importa ahora.</h1><p>Agenda, tareas y compromisos detectados convergen acá. SOL propone; vos decidís qué se convierte en acción.</p>
<section id="brief" class="card"><p class="muted">Preparando brief…</p></section>
<section id="morning" class="card"><h2>Morning Brief</h2><p class="muted">Cargando configuración…</p></section>
<section id="proposals" class="card"><p class="muted">Cargando propuestas…</p></section>
</main><script>
const brief=document.getElementById('brief'),proposals=document.getElementById('proposals');const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));async function api(path,options={}){const r=await fetch(path,{cache:'no-store',...options});let b={};try{b=await r.json()}catch{}return{response:r,body:b}}
const morning=document.getElementById('morning');
async function loadMorning(){const r=await api('/v1/executive/morning-brief/status');if(!r.response.ok){morning.innerHTML='<h2>Morning Brief</h2><p class="error">'+esc(r.body.error||'No disponible')+'</p>';return}const s=r.body.settings,last=r.body.lastRun;morning.innerHTML='<div class="row"><div><h2>Morning Brief</h2><div class="muted">Un resumen diario integrado, auditable e idempotente.</div></div><label><input id="mbEnabled" type="checkbox" '+(s.morningBriefEnabled?'checked':'')+'> Habilitado</label></div><div class="actions"><label>Hora <input id="mbTime" type="time" value="'+esc(s.morningTime)+'"></label><label>Timezone <input id="mbZone" value="'+esc(s.morningTimezone)+'"></label></div><div class="actions"><label><input id="mbGmail" type="checkbox" '+(s.morningSources.gmail?'checked':'')+'> Gmail</label><label><input id="mbWa" type="checkbox" '+(s.morningSources.whatsapp?'checked':'')+'> WhatsApp</label><label><input id="mbMl" type="checkbox" '+(s.morningSources.mercadolibre?'checked':'')+'> MercadoLibre</label><label><input id="mbCal" type="checkbox" '+(s.morningSources.calendar?'checked':'')+'> Calendar</label></div><div class="actions"><label><input id="mbEvents" type="checkbox" '+(s.morningAutoCreateEvents?'checked':'')+'> Crear eventos claros</label><label><input id="mbSend" type="checkbox" '+(s.morningSendWhatsapp?'checked':'')+'> Enviar por WhatsApp</label><label><input id="mbGrant" type="checkbox" '+(s.morningWhatsappGrant?'checked':'')+'> Grant proactivo explícito</label></div><div class="actions"><button id="mbSave">Guardar</button><button class="secondary" id="mbPreview">Vista previa</button><button class="secondary" id="mbRun">Probar ahora</button></div><pre id="mbResult">'+esc(last?('Última ejecución: '+last.status+' · '+last.startedAt):'Todavía no hay ejecuciones.')+'</pre>';document.getElementById('mbSave').onclick=async()=>{const body={morningBriefEnabled:mbEnabled.checked,morningTime:mbTime.value,morningTimezone:mbZone.value,morningSources:{gmail:mbGmail.checked,whatsapp:mbWa.checked,mercadolibre:mbMl.checked,calendar:mbCal.checked},morningAutoCreateEvents:mbEvents.checked,morningSendWhatsapp:mbSend.checked,morningWhatsappGrant:mbGrant.checked};const x=await api('/v1/executive/proactivity',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});mbResult.textContent=x.response.ok?'Configuración guardada.':(x.body.error||'Error')};const run=async dry=>{mbResult.textContent='Ejecutando…';const x=await api('/v1/executive/morning-brief/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({dryRun:dry})});mbResult.textContent=x.response.ok?(x.body.run.summary||x.body.run.status):x.body.error};mbPreview.onclick=()=>run(true);mbRun.onclick=()=>run(false)}
function when(p){const v=p.startsAt||p.dueAt;return v?new Date(v).toLocaleString():'sin fecha definida'}
async function loadBrief(refresh=false){const r=await api('/v1/executive/brief?type=morning'+(refresh?'&refresh=1':''));if(!r.response.ok){brief.innerHTML='<h2>Brief de hoy</h2><p class="error">'+esc(r.body.error||'No disponible')+'</p>';return}const b=r.body.brief;brief.innerHTML='<div class="row"><div><h2>Brief de hoy</h2><div class="muted">'+esc(new Date(b.periodStart).toLocaleDateString())+'</div></div><button class="secondary" id="refresh">Actualizar</button></div><pre>'+esc(b.summary)+'</pre><div class="brief-grid"><div class="stat"><b>'+b.events.length+'</b>eventos</div><div class="stat"><b>'+b.tasks.length+'</b>tareas</div><div class="stat"><b>'+b.conflicts.length+'</b>conflictos</div></div>';document.getElementById('refresh').onclick=()=>loadBrief(true)}
async function loadProposals(){const r=await api('/v1/executive/proposals?status=pending');if(!r.response.ok){proposals.innerHTML='<p class="error">'+esc(r.body.error||'Error')+'</p>';return}const items=r.body.proposals||[];proposals.innerHTML='<div class="row"><div><h2>Por confirmar</h2><div class="muted">Compromisos, eventos y tareas detectados</div></div><span class="pill">'+items.length+'</span></div>'+(items.map(p=>'<div class="proposal"><div class="row"><div><strong>'+esc(p.title)+'</strong><div class="muted">'+esc(p.kind)+' · '+Math.round((p.confidence||0)*100)+'% · '+esc(when(p))+'</div></div><span class="pill">'+esc(p.ownerMemberId?'personal':'familiar')+'</span></div>'+(p.summary?'<p>'+esc(p.summary)+'</p>':'')+'<div class="actions"><button data-approve="'+esc(p.id)+'">Aprobar</button><button class="secondary" data-reject="'+esc(p.id)+'">Descartar</button></div></div>').join('')||'<p class="muted">No hay propuestas pendientes.</p>');document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{b.disabled=true;const x=await api('/v1/executive/proposals/'+b.dataset.approve+'/approve',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});if(!x.response.ok){alert(x.body.error==='calendar_target_required'?'Elegí primero un calendario de escritura en Calendar.':x.body.error||'No se pudo aprobar');b.disabled=false;return}await Promise.all([loadBrief(true),loadProposals()])});document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=async()=>{b.disabled=true;await api('/v1/executive/proposals/'+b.dataset.reject+'/reject',{method:'POST'});await loadProposals()})}
async function load(){const me=await api('/v1/auth/me');if(!me.response.ok){brief.innerHTML='<p><a href="/">Iniciá sesión</a></p>';proposals.innerHTML='';morning.innerHTML='';return}await Promise.all([loadBrief(false),loadMorning(),loadProposals()])}load();
</script></body></html>`;
}
