export function renderHomeAssistantPage(): string {
  return `<!doctype html>
<html lang="es"><head>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>SOL · Home Assistant</title>
<style>
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText}main{width:min(980px,calc(100% - 28px));margin:auto;padding:38px 0 80px}.top,.row,.actions,.toolbar{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.top,.row,.toolbar{justify-content:space-between}.brand{font-size:13px;font-weight:900;letter-spacing:.17em;opacity:.65}nav{display:flex;gap:14px;flex-wrap:wrap;font-size:14px}a{color:inherit}h1{font-size:clamp(38px,7vw,64px);letter-spacing:-.05em;margin:15px 0 7px}h2{margin:0 0 8px}.muted{opacity:.63}p{line-height:1.55}.card{padding:20px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:19px;margin:14px 0}.pill{font-size:12px;padding:5px 9px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);border-radius:999px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:6px;font-size:13px;font-weight:700}input,select{padding:11px 12px;border-radius:11px;border:1px solid color-mix(in srgb,CanvasText 20%,transparent);background:Canvas;color:CanvasText;font:inherit}button{padding:10px 14px;border-radius:999px;border:0;background:CanvasText;color:Canvas;font:inherit;font-weight:800;cursor:pointer}button.secondary{background:transparent;color:CanvasText;border:1px solid color-mix(in srgb,CanvasText 20%,transparent)}.entity{display:grid;grid-template-columns:auto minmax(180px,1fr) auto auto;gap:12px;align-items:center;padding:10px 0;border-top:1px solid color-mix(in srgb,CanvasText 9%,transparent)}.entity:first-child{border-top:0}.entity small{display:block;opacity:.58;overflow-wrap:anywhere}.state{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}.error{color:#d33}.search{width:min(380px,100%)}@media(max-width:720px){.grid{grid-template-columns:1fr}.entity{grid-template-columns:auto 1fr}.entity select,.entity .state{grid-column:2}.top{align-items:flex-start}}
</style></head><body><main>
<div class="top"><div class="brand">SOL · HOME ASSISTANT</div><nav><a href="/">Inicio</a><a href="/life">Vida</a><a href="/sol-whatsapp">WhatsApp de SOL</a></nav></div>
<h1>La casa como fuente.</h1>
<p class="muted">SOL escucha sólo las entidades que elegís. Esta primera versión es deliberadamente de lectura: no ejecuta servicios ni controla dispositivos.</p>
<section id="app"><p class="muted">Cargando…</p></section>
</main><script>
const app=document.getElementById('app');let me,accounts=[];function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}async function api(path,o={}){const r=await fetch(path,{cache:'no-store',...o});let b={};try{b=await r.json()}catch{}return{r,b}}function manager(){return me&&(me.role==='owner'||me.role==='adult')}function stateLabel(v){return({idle:'detenido',connecting:'conectando',open:'en vivo',reconnecting:'reconectando',error:'error'})[v]||v}
async function load(){const [m,a]=await Promise.all([api('/v1/auth/me'),api('/v1/home-assistant/accounts')]);if(!m.r.ok){app.innerHTML='<div class="card"><h2>Necesitás iniciar sesión</h2><a href="/">Volver</a></div>';return}me=m.b.member;if(!a.r.ok){app.innerHTML='<div class="card error">'+esc(a.b.error||'No disponible')+'</div>';return}accounts=a.b.accounts||[];render()}
function render(){let html='';if(manager())html+='<div class="card"><h2>Agregar Home Assistant</h2><p class="muted">Creá un Long-Lived Access Token en tu perfil de Home Assistant. SOL lo cifra localmente antes de guardarlo en PostgreSQL.</p><form id="add"><div class="grid"><label>Nombre<input name="label" value="Casa" maxlength="120"></label><label>URL<input name="baseUrl" placeholder="http://homeassistant.local:8123" required></label><label style="grid-column:1/-1">Long-Lived Access Token<input name="token" type="password" autocomplete="off" required></label></div><button>Conectar</button><span id="addstatus" class="muted"></span></form></div>';html+=accounts.map(accountCard).join('');if(!accounts.length&&!manager())html+='<div class="card"><p class="muted">Todavía no hay una instancia de Home Assistant configurada.</p></div>';app.innerHTML=html;const add=document.getElementById('add');if(add)add.onsubmit=async e=>{e.preventDefault();const s=document.getElementById('addstatus');s.textContent='Probando conexión…';const d=Object.fromEntries(new FormData(add).entries());const out=await api('/v1/home-assistant/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(d)});if(!out.r.ok){s.className='error';s.textContent=out.b.error||'Error';return}add.reset();await load()};accounts.forEach(wire)}
function accountCard(a){const rt=a.runtime||{};return '<div class="card" id="acc-'+esc(a.id)+'"><div class="row"><div><h2>'+esc(a.label)+'</h2><div class="muted">'+esc(a.baseUrl)+(a.haVersion?' · HA '+esc(a.haVersion):'')+'</div></div><span class="pill">'+esc(stateLabel(rt.state))+'</span></div>'+(a.lastError?'<p class="error">'+esc(a.lastError)+'</p>':'')+(manager()?'<div class="actions"><button class="secondary discover">Redescubrir entidades</button><button class="secondary restart">Reconectar</button></div>':'')+'<div class="toolbar" style="margin-top:18px"><input class="search" placeholder="Buscar entidad…"><span class="muted selected-count">'+esc(rt.selectedEntities||0)+' seleccionadas</span></div><div class="entities"><p class="muted">Cargando entidades…</p></div></div>'}
async function wire(a){const root=document.getElementById('acc-'+a.id),box=root.querySelector('.entities'),search=root.querySelector('.search');let entities=[];async function fetchEntities(){const out=await api('/v1/home-assistant/accounts/'+a.id+'/entities');if(!out.r.ok){box.innerHTML='<p class="error">'+esc(out.b.error||'Error')+'</p>';return}entities=out.b.entities||[];draw()}function draw(){const q=(search.value||'').toLowerCase();const shown=entities.filter(e=>!q||e.entityId.toLowerCase().includes(q)||(e.friendlyName||'').toLowerCase().includes(q)).slice(0,350);box.innerHTML=shown.length?shown.map(entityRow).join(''):'<p class="muted">No hay coincidencias.</p>';if(manager())box.querySelectorAll('.sync').forEach(el=>el.onchange=()=>save(el.dataset.id,el.checked,root.querySelector('select[data-id="'+CSS.escape(el.dataset.id)+'"]').value));if(manager())box.querySelectorAll('.mode').forEach(el=>el.onchange=()=>save(el.dataset.id,root.querySelector('input[data-id="'+CSS.escape(el.dataset.id)+'"]').checked,el.value))}async function save(id,selected,mode){const out=await api('/v1/home-assistant/accounts/'+a.id+'/entities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entityId:id,selectedForSync:selected,recordMode:mode})});if(out.r.ok){const item=entities.find(e=>e.entityId===id);if(item){item.selectedForSync=selected;item.recordMode=mode}root.querySelector('.selected-count').textContent=entities.filter(e=>e.selectedForSync).length+' seleccionadas'}}search.oninput=draw;if(manager()){root.querySelector('.discover').onclick=async()=>{root.querySelector('.discover').disabled=true;await api('/v1/home-assistant/accounts/'+a.id+'/discover',{method:'POST'});await fetchEntities();root.querySelector('.discover').disabled=false};root.querySelector('.restart').onclick=async()=>{await api('/v1/home-assistant/accounts/'+a.id+'/restart',{method:'POST'});await load()}}await fetchEntities()}
function entityRow(e){const checked=e.selectedForSync?'checked':'';const disabled=manager()?'':'disabled';return '<div class="entity"><input class="sync" data-id="'+esc(e.entityId)+'" type="checkbox" '+checked+' '+disabled+'><div><strong>'+esc(e.friendlyName||e.entityId)+'</strong><small>'+esc(e.entityId)+' · '+esc(e.domain)+(e.deviceClass?' · '+esc(e.deviceClass):'')+'</small></div><span class="state">'+esc(e.currentState||'—')+(e.unitOfMeasurement?' '+esc(e.unitOfMeasurement):'')+'</span><select class="mode" data-id="'+esc(e.entityId)+'" '+disabled+'><option value="changes" '+(e.recordMode==='changes'?'selected':'')+'>Guardar cambios</option><option value="snapshot" '+(e.recordMode==='snapshot'?'selected':'')+'>Sólo estado actual</option></select></div>'}
load();
</script></body></html>`;
}
