import { solPage } from "./shell.js";

export function renderInputsPage(): string {
  const body = `<section class="page">
    <div class="toolbar"><div><div class="eyebrow">SOL · Inputs</div><h1>Todo lo que entra.</h1><p class="lead">Una sola pantalla para conectar, verificar y administrar las fuentes que alimentan Life y Knowledge. Cada input conserva su procedencia y privacidad.</p></div><button class="primary" id="add-input">+ Agregar input</button></div>
    <div id="summary" class="grid" style="margin-bottom:16px"><div class="card span4"><div class="stat">—</div><div class="label">inputs</div></div><div class="card span4"><div class="stat">—</div><div class="label">ítems 24 h</div></div><div class="card span4"><div class="stat">—</div><div class="label">estado</div></div></div>
    <section id="inputs"><div class="empty">Cargando inputs…</div></section>
  </section>
  <dialog id="modal"><div class="dialogbody"><div class="dialoghead"><div><div class="eyebrow" id="modal-eye">Input</div><h2 id="modal-title">Agregar input</h2></div><button id="modal-close">✕</button></div><div id="modal-body"></div></div></dialog>`;

  const script = `
const root=document.getElementById('inputs'), summary=document.getElementById('summary'), modal=document.getElementById('modal'), modalBody=document.getElementById('modal-body');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function api(path,o={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(path,{cache:'no-store',...o,signal:controller.signal});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(timer)}}
function fmt(v){if(!v)return 'Nunca';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function providerLabel(p){return({whatsapp:'WhatsApp',gmail:'Gmail',google_calendar:'Google Calendar',home_assistant:'Home Assistant',mercadolibre:'Mercado Libre'})[p]||p}
function providerGlyph(p){return({whatsapp:'W',gmail:'G',google_calendar:'C',home_assistant:'H',mercadolibre:'M'})[p]||'•'}
function detailHref(p){return({whatsapp:'/whatsapp?advanced=1',google_calendar:'/calendar?advanced=1',home_assistant:'/home-assistant?advanced=1',mercadolibre:'/mercadolibre?advanced=1'})[p]||''}
function stateOf(x){const s=x.runtime?.state||x.status;if(['open','connected'].includes(s))return['good','activo'];if(['connecting','reconnecting','qr'].includes(s))return['warn',s==='qr'?'esperando vínculo':'conectando'];if(['error','logged_out'].includes(s))return['bad',s];return['','inactivo']}
function providerActions(x){if(!x.canManage)return '';if(x.provider==='gmail'){if(x.status==='disconnected')return '<button data-gmail-connect="'+esc(x.id)+'">Conectar Gmail</button>';return '<button data-gmail-sync="'+esc(x.id)+'">Sincronizar</button><button data-gmail-disconnect="'+esc(x.id)+'">Desconectar</button>'}const href=detailHref(x.provider);return href?'<a class="button" href="'+href+'">Ajustes avanzados</a>':''}
function card(x){const [dot,state]=stateOf(x),st=x.stats||{},last=st.lastObservedAt||st.lastItemAt||x.lastSyncAt;return '<article class="card" style="margin-bottom:12px"><div class="row between"><div class="cluster"><div style="width:38px;height:38px;border-radius:12px;background:#202632;display:grid;place-items:center;font-weight:900">'+esc(providerGlyph(x.provider))+'</div><div><h2>'+esc(x.label)+'</h2><div class="muted small">'+esc(providerLabel(x.provider))+' · '+(x.shared?'familiar':'personal')+(x.externalAccountId?' · '+esc(x.externalAccountId):'')+'</div></div></div><span class="badge"><span class="dot '+dot+'"></span>'+esc(state)+'</span></div><div class="grid" style="margin-top:16px"><div class="span4"><div class="stat" style="font-size:22px">'+Number(st.totalItems||0).toLocaleString('es-AR')+'</div><div class="label">ítems en Life</div></div><div class="span4"><div class="stat" style="font-size:22px">'+Number(st.items24h||0).toLocaleString('es-AR')+'</div><div class="label">últimas 24 h</div></div><div class="span4"><div class="stat" style="font-size:15px;margin-top:4px">'+esc(fmt(last))+'</div><div class="label">último dato recibido</div></div></div>'+(x.runtime?.lastError?'<div class="card soft error small" style="margin-top:14px">'+esc(x.runtime.lastError)+'</div>':'')+'<div class="cluster" style="margin-top:16px"><button data-feed="'+esc(x.id)+'">Ver feed</button>'+(x.canManage?'<button data-edit="'+esc(x.id)+'">Editar</button>':'')+providerActions(x)+(x.canManage?'<button class="danger" data-remove="'+esc(x.id)+'">Eliminar</button>':'')+'</div></article>'}
let current=[];
async function load(){const out=await api('/v1/inputs');if(!out.r.ok){root.innerHTML='<div class="empty error">'+esc(out.b.error||'No se pudieron cargar los inputs')+'</div>';return}current=out.b.inputs||[];const total24=current.reduce((n,x)=>n+Number(x.stats?.items24h||0),0),active=current.filter(x=>stateOf(x)[1]==='activo').length;summary.innerHTML='<div class="card span4"><div class="stat">'+current.length+'</div><div class="label">inputs visibles</div></div><div class="card span4"><div class="stat">'+total24.toLocaleString('es-AR')+'</div><div class="label">ítems recibidos en 24 h</div></div><div class="card span4"><div class="stat">'+active+'/'+current.length+'</div><div class="label">inputs activos</div></div>';root.innerHTML=current.length?current.map(card).join(''):'<div class="empty">Todavía no agregaste ningún input.</div>';bind()}
function openDialog(title,html,eye='Input'){document.getElementById('modal-title').textContent=title;document.getElementById('modal-eye').textContent=eye;modalBody.innerHTML=html;modal.showModal()}
document.getElementById('modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});document.getElementById('add-input').onclick=()=>showAdd();
function showAdd(){openDialog('Agregar input','<div class="grid"><button class="card span6" data-provider="whatsapp" style="text-align:left"><h2>WhatsApp</h2><p class="muted">Mensajes e historial observados.</p></button><button class="card span6" data-provider="gmail" style="text-align:left"><h2>Gmail</h2><p class="muted">Correos recientes en modo sólo lectura.</p></button><button class="card span6" data-provider="google_calendar" style="text-align:left"><h2>Google Calendar</h2><p class="muted">Eventos de calendarios seleccionados.</p></button><button class="card span6" data-provider="home_assistant" style="text-align:left"><h2>Home Assistant</h2><p class="muted">Estados y cambios seleccionados.</p></button><button class="card span6" data-provider="mercadolibre" style="text-align:left"><h2>Mercado Libre</h2><p class="muted">Ventas, publicaciones y preguntas.</p></button></div>','Nuevo input');document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>providerForm(b.dataset.provider))}
function providerForm(provider){const label=providerLabel(provider);if(provider==='home_assistant'){openDialog('Conectar '+label,'<form id="provider-form"><label>Nombre<input name="label" value="Home Assistant casa" required></label><label style="margin-top:10px">URL<input name="baseUrl" placeholder="http://homeassistant.local:8123" required></label><label style="margin-top:10px">Long-Lived Access Token<input name="token" type="password" required></label><div class="cluster" style="margin-top:14px"><button class="primary">Conectar</button><span id="form-status" class="muted"></span></div></form>','Nuevo input')}else{openDialog('Conectar '+label,'<form id="provider-form"><label>Nombre<input name="label" value="'+esc(label+(provider==='whatsapp'||provider==='gmail'?' personal':''))+'" required></label><label style="margin-top:10px">Propiedad<select name="shared"><option value="false">Personal</option><option value="true">Familiar</option></select></label>'+(provider==='gmail'?'<p class="small muted">SOL solicitará únicamente permiso Gmail de lectura. No podrá enviar, borrar ni marcar correos.</p>':'')+'<div class="cluster" style="margin-top:14px"><button class="primary">Continuar</button><span id="form-status" class="muted"></span></div></form>','Nuevo input')}document.getElementById('provider-form').onsubmit=e=>submitProvider(e,provider)}
async function submitProvider(e,provider){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries()),s=document.getElementById('form-status');s.textContent='Conectando…';let path,payload;if(provider==='whatsapp'){path='/v1/whatsapp/accounts';payload={label:d.label,shared:d.shared==='true'}}if(provider==='gmail'){path='/v1/gmail/accounts';payload={label:d.label,shared:d.shared==='true'}}if(provider==='google_calendar'){path='/v1/calendar/accounts';payload={label:d.label,shared:d.shared==='true'}}if(provider==='home_assistant'){path='/v1/home-assistant/accounts';payload={label:d.label,baseUrl:d.baseUrl,token:d.token}}if(provider==='mercadolibre'){path='/v1/mercadolibre/accounts';payload={label:d.label,shared:d.shared==='true'}}if(!path){s.className='error';s.textContent='Proveedor no soportado';return}const out=await api(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});if(!out.r.ok){s.className='error';s.textContent=out.b.error||'No se pudo conectar';return}if(['gmail','google_calendar','mercadolibre'].includes(provider)){location.href=out.b.login.authorizationUrl;return}if(provider==='whatsapp'){await beginWhatsapp(out.b.account?.id||out.b.sourceAccount?.id);return}modal.close();await load()}
async function beginWhatsapp(id){if(!id){modal.close();await load();return}openDialog('Vincular WhatsApp','<div id="wa-link"><p class="muted">Iniciando conexión…</p></div>','WhatsApp');const out=await api('/v1/whatsapp/accounts/'+encodeURIComponent(id)+'/connect',{method:'POST'});if(!out.r.ok){document.getElementById('wa-link').innerHTML='<p class="error">'+esc(out.b.error||'No se pudo iniciar')+'</p>';return}await pollWhatsapp(id)}
async function pollWhatsapp(id){for(let n=0;n<45;n++){const out=await api('/v1/whatsapp/accounts/'+encodeURIComponent(id)+'/status');if(out.r.ok){const r=out.b.account?.runtime||out.b.runtime||{};if(r.state==='open'){document.getElementById('wa-link').innerHTML='<h2 class="goodtext">WhatsApp conectado</h2><p class="muted">Los mensajes nuevos deberían empezar a aparecer en Life.</p>';await load();return}if(r.qrDataUrl){document.getElementById('wa-link').innerHTML='<p class="muted">Escaneá este QR desde WhatsApp → Dispositivos vinculados.</p><div style="background:white;padding:12px;border-radius:16px;width:max-content;max-width:100%"><img src="'+esc(r.qrDataUrl)+'" style="display:block;max-width:280px;width:100%"></div><p class="small muted">Estado: '+esc(r.state)+'</p>'}if(r.lastError){document.getElementById('wa-link').innerHTML+='<p class="error">'+esc(r.lastError)+'</p>'}}await new Promise(r=>setTimeout(r,1000))}}
function bind(){document.querySelectorAll('[data-feed]').forEach(b=>b.onclick=()=>showFeed(b.dataset.feed));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>showEdit(b.dataset.edit));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeInput(b.dataset.remove));document.querySelectorAll('[data-gmail-sync]').forEach(b=>b.onclick=()=>gmailAction(b.dataset.gmailSync,'sync'));document.querySelectorAll('[data-gmail-connect]').forEach(b=>b.onclick=()=>gmailAction(b.dataset.gmailConnect,'connect'));document.querySelectorAll('[data-gmail-disconnect]').forEach(b=>b.onclick=()=>gmailAction(b.dataset.gmailDisconnect,'disconnect'))}
async function gmailAction(id,action){const out=await api('/v1/gmail/accounts/'+encodeURIComponent(id)+'/'+action,{method:'POST'});if(!out.r.ok){alert(out.b.error||'No se pudo actualizar Gmail');return}if(action==='connect'){location.href=out.b.login.authorizationUrl;return}await load()}
async function showFeed(id){const x=current.find(v=>v.id===id);openDialog('Feed · '+(x?.label||''),'<div class="empty">Cargando registros…</div>','Datos recibidos');const out=await api('/v1/inputs/'+encodeURIComponent(id)+'/items?limit=100');if(!out.r.ok){modalBody.innerHTML='<div class="empty error">'+esc(out.b.error||'Error')+'</div>';return}const items=out.b.items||[];modalBody.innerHTML=items.length?'<div class="feed">'+items.map(i=>'<div class="feeditem"><div class="row between"><strong>'+esc(i.metadata?.pushName||i.metadata?.from||i.title||i.kind)+'</strong><span class="small muted">'+esc(fmt(i.occurredAt))+'</span></div>'+(i.title&&i.metadata?.from?'<div class="small" style="margin-top:4px"><strong>'+esc(i.title)+'</strong></div>':'')+(i.text?'<div class="feedtext">'+esc(i.text)+'</div>':'<div class="muted small">Sin texto · '+esc(i.metadata?.messageType||i.kind)+'</div>')+'<div class="small muted" style="margin-top:5px">'+esc(i.metadata?.origin||'')+(i.metadata?.fromMe?' · enviado por vos':'')+'</div></div>').join('')+'</div>':'<div class="empty">Este input todavía no produjo ningún source_item. Si está conectado, revisá su estado o forzá una sincronización.</div>'}
function showEdit(id){const x=current.find(v=>v.id===id);if(!x)return;openDialog('Editar '+x.label,'<form id="edit-form"><label>Nombre<input name="label" value="'+esc(x.label)+'" required></label><label style="margin-top:10px">Propiedad<select name="shared"><option value="false" '+(!x.shared?'selected':'')+'>Personal</option><option value="true" '+(x.shared?'selected':'')+'>Familiar</option></select></label><p class="muted small">Cambiar la propiedad actualiza la visibilidad de los registros ya importados de este origen.</p><div class="cluster"><button class="primary">Guardar cambios</button><span id="edit-status" class="muted"></span></div></form>','Configuración');document.getElementById('edit-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),st=document.getElementById('edit-status');st.textContent='Guardando…';const out=await api('/v1/inputs/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({label:d.label,shared:d.shared==='true'})});if(!out.r.ok){st.className='error';st.textContent=out.b.error||'Error';return}modal.close();await load()}}
async function removeInput(id){const x=current.find(v=>v.id===id);if(!x)return;if(!confirm('Eliminar “'+x.label+'” también borrará de SOL los datos importados desde este origen. ¿Continuar?'))return;const out=await api('/v1/inputs/'+encodeURIComponent(id),{method:'DELETE'});if(!out.r.ok){alert(out.b.error||'No se pudo eliminar');return}await load()}
load();setInterval(()=>{if(!document.hidden)load().catch(()=>{})},15000);
`;
  return solPage("inputs", "Inputs", body, script);
}
