import { solPage } from "./shell.js";

export function renderInputsPage(): string {
  const body = `<section class="page">
    <div class="toolbar">
      <div>
        <div class="eyebrow">SOL</div>
        <h1 id="page-title">Conexiones.</h1>
        <p class="lead" id="page-lead">Todo lo que vinculaste con SOL, ordenado por servicio y cuenta. Acá importa qué está conectado; los detalles de runtime quedan en Sistema.</p>
      </div>
      <div class="cluster"><a class="button" href="/v1/inputs/plugins/ui">Sistema y plugins</a></div>
    </div>

    <div class="seg" style="width:max-content;margin-bottom:18px">
      <button id="tab-connections" data-view="connections">Conexiones</button>
      <button id="tab-people" data-view="people">Personas</button>
    </div>

    <div id="connections-view">
      <div id="connection-summary" class="grid" style="margin-bottom:14px"></div>
      <section class="card span12" style="margin-bottom:14px">
        <div class="row between"><div><div class="kicker">Servicios</div><h2 style="margin-top:4px">Tus conectores</h2></div><a class="button" href="/v1/inputs/plugins/ui">Administrar plugins</a></div>
        <div class="divider"></div><div id="plugin-list"><div class="empty">Cargando conectores…</div></div>
      </section>
      <section class="card span12">
        <div class="row between"><div><div class="kicker">Cuentas y fuentes</div><h2 style="margin-top:4px">Qué datos llegan a SOL</h2></div><span class="badge">cada fila = una conexión real</span></div>
        <p class="muted small">Para quitar una cuenta administrada por un plugin, hacelo desde ese plugin. Si la cuenta ya no existe pero quedó una fila vieja desconectada, SOL ofrece <strong>Quitar residuo</strong>.</p>
        <div class="divider"></div><div id="input-list"><div class="empty">Cargando conexiones…</div></div>
      </section>
    </div>

    <div id="people-view" hidden>
      <div class="callout small" style="margin-bottom:14px"><strong>Una Persona, muchas identidades.</strong> WhatsApp, Home Assistant, una futura voz reconocida por Audio Remote y otras cuentas pueden apuntar al mismo humano. Vincular una identidad <strong>no otorga acceso ni permisos</strong> a SOL.</div>
      <div class="grid">
        <section class="card span4"><div class="row between"><div><div class="kicker">Acceso</div><h2 style="margin-top:4px">Miembros del hogar</h2></div><span class="badge" id="member-count">—</span></div><p class="muted small">Personas con login y rol de permisos. Esto es independiente de sus identidades externas.</p><div class="divider"></div><div id="members"><div class="empty">Cargando…</div></div></section>
        <section class="card span8"><div class="row between"><div><div class="kicker">Identidad canónica</div><h2 style="margin-top:4px">Personas e identidades vinculadas</h2></div><span class="badge" id="known-count">—</span></div><p class="muted small">Cada identidad externa pertenece a una sola Persona; una Persona puede tener muchas identidades de distintos plugins.</p><div class="divider"></div><div id="known-people"><div class="empty">Cargando…</div></div></section>
        <section class="card span12"><div class="row between"><div><div class="kicker">Regla de seguridad</div><h2 style="margin-top:4px">Reconocer no es autenticar</h2></div></div><div class="divider"></div><div class="grid"><div class="span4"><h3>Nexo / WhatsApp</h3><p class="muted small">Un teléfono puede vincularse a una Persona canónica. Nexo sigue decidiendo por separado quién puede conversar por WhatsApp.</p><button data-open-plugin="nexo">Abrir Nexo</button></div><div class="span4"><h3>Home Assistant</h3><p class="muted small">Las entidades <code>person.*</code> pueden vincularse a la misma Persona que un teléfono u otra identidad.</p><a class="button" href="/v1/inputs/plugins/ui">Configurar plugin</a></div><div class="span4"><h3>Audio Remote</h3><p class="muted small">Una futura huella de voz podrá resolver a esta misma Persona, pero por sí sola no concederá login, rol ni autorización.</p><a class="button" href="/v1/inputs/plugins/ui">Configurar plugin</a></div></div></section>
      </div>
    </div>

    <dialog id="items-dialog"><div class="dialogbody"><div class="dialoghead"><div><div class="eyebrow">Actividad reciente</div><h2 id="items-title">Conexión</h2></div><button id="items-close">✕</button></div><div id="items-feed" class="feed"></div></div></dialog>
  </section>`;

  const script = `
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
async function api(path,o={}){try{const r=await fetch(path,{cache:'no-store',...o});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.message||'Error de conexión'}}}}
const state={inputs:[],plugins:[],people:[],canManagePlugins:false};
function fmt(v){if(!v)return 'sin actividad';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return String(v)}}
function statusClass(s){return s==='connected'||s==='open'||s==='running'?'good':s==='error'||s==='unhealthy'?'bad':'warn'}
function pluginPanelUrl(p){const d=p.healthDetails||p.details||{};return d.bridgeUrl||d.dashboardUrl||d.uiUrl||null}
function pluginCard(p){const m=p.manifest||{},url=pluginPanelUrl(p),health=p.health||p.state||'unknown';return '<div class="accountline"><div><div class="row"><strong>'+esc(m.name||m.id||'Plugin')+'</strong><span class="badge"><span class="dot '+statusClass(p.state==='running'?health:p.state)+'"></span>'+esc(p.state==='running'?health:p.state||'instalado')+'</span></div><div class="small muted" style="margin-top:4px">'+esc(m.description||'Conector de SOL')+'</div></div><div class="cluster">'+(url?'<a class="button primary" href="'+esc(url)+'" target="_blank" rel="noreferrer">Abrir panel</a>':'')+'<a class="button" href="/v1/inputs/plugins/ui">Configurar</a></div></div>'}
function inputCard(x){const plugin=!!x.pluginManaged,st=x.stats||{},meta=[x.provider,x.shared?'compartida':'personal',plugin?'plugin '+(x.pluginId||''):'integrada'].filter(Boolean).join(' · ');let actions='<button data-items="'+esc(x.id)+'" data-label="'+esc(x.label)+'">Ver actividad</button>';if(x.canManage){if(plugin){actions+='<a class="button" href="/v1/inputs/plugins/ui">Administrar plugin</a>';if(x.canCleanupResidual)actions+='<button class="danger" data-clean="'+esc(x.id)+'" data-label="'+esc(x.label)+'">Quitar residuo</button>'}else actions+='<button class="danger" data-delete="'+esc(x.id)+'" data-label="'+esc(x.label)+'">Quitar conexión</button>'}return '<div class="accountline"><div><div class="row"><strong>'+esc(x.label)+'</strong><span class="badge"><span class="dot '+statusClass(x.status)+'"></span>'+esc(x.status)+'</span></div><div class="small muted" style="margin-top:4px">'+esc(meta)+' · '+Number(st.items24h||0)+' items/24 h · último '+esc(fmt(st.lastObservedAt||x.lastSyncAt))+'</div>'+(plugin&&x.status!=='connected'?'<div class="warntext small" style="margin-top:5px">Si esta cuenta ya fue eliminada en el plugin, podés limpiar solamente el residuo de SOL.</div>':'')+'</div><div class="cluster">'+actions+'</div></div>'}
function renderConnections(){const active=state.inputs.filter(x=>x.status==='connected').length,residual=state.inputs.filter(x=>x.canCleanupResidual).length,running=state.plugins.filter(x=>x.state==='running').length;document.getElementById('connection-summary').innerHTML='<div class="card span4"><div class="stat">'+active+'/'+state.inputs.length+'</div><div class="label">conexiones activas</div></div><div class="card span4"><div class="stat">'+running+'/'+state.plugins.length+'</div><div class="label">plugins ejecutándose</div></div><div class="card span4"><div class="stat">'+residual+'</div><div class="label">residuos limpiables</div></div>';document.getElementById('plugin-list').innerHTML=state.plugins.length?state.plugins.map(pluginCard).join(''):'<div class="empty">Todavía no instalaste conectores.</div>';document.getElementById('input-list').innerHTML=state.inputs.length?state.inputs.map(inputCard).join(''):'<div class="empty">Todavía no hay cuentas conectadas.</div>';bindConnectionActions()}
async function loadConnections(){const [ir,pr]=await Promise.all([api('/v1/inputs'),api('/v1/inputs/plugins')]);if(ir.r.ok)state.inputs=ir.b.inputs||[];if(pr.r.ok){state.plugins=pr.b.plugins||[];state.canManagePlugins=!!pr.b.canManage}renderConnections()}
function bindConnectionActions(){document.querySelectorAll('[data-items]').forEach(b=>b.onclick=()=>showItems(b.dataset.items,b.dataset.label));document.querySelectorAll('[data-clean]').forEach(b=>b.onclick=()=>cleanup(b.dataset.clean,b.dataset.label));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeInput(b.dataset.delete,b.dataset.label))}
async function cleanup(id,label){if(!confirm('¿Quitar el residuo “'+label+'” de SOL? Esto borra su proyección y datos ingeridos en SOL. La cuenta real del plugin no se toca.'))return;const out=await api('/v1/inputs/'+encodeURIComponent(id)+'?cleanup=1',{method:'DELETE'});if(!out.r.ok){alert(out.b.error||'No se pudo limpiar');return}await loadConnections()}
async function removeInput(id,label){if(!confirm('¿Quitar la conexión “'+label+'” y sus datos guardados en SOL?'))return;const out=await api('/v1/inputs/'+encodeURIComponent(id),{method:'DELETE'});if(!out.r.ok){alert(out.b.hint||out.b.error||'No se pudo quitar');return}await loadConnections()}
async function showItems(id,label){document.getElementById('items-title').textContent=label||'Conexión';const feed=document.getElementById('items-feed');feed.innerHTML='<div class="empty">Cargando…</div>';document.getElementById('items-dialog').showModal();const out=await api('/v1/inputs/'+encodeURIComponent(id)+'/items?limit=60');if(!out.r.ok){feed.innerHTML='<div class="empty error">'+esc(out.b.error||'Error')+'</div>';return}const items=out.b.items||[];feed.innerHTML=items.length?items.map(i=>'<div class="feeditem"><div class="small muted">'+esc(fmt(i.occurredAt))+' · '+esc(i.kind)+'</div><strong>'+esc(i.title||'Sin título')+'</strong>'+(i.text?'<div class="feedtext small">'+esc(i.text)+'</div>':'')+'</div>').join(''):'<div class="empty">Sin actividad guardada.</div>'}
document.getElementById('items-close').onclick=()=>document.getElementById('items-dialog').close();
function memberRow(m){return '<div class="accountline"><div><strong>'+esc(m.displayName)+'</strong><div class="small muted" style="margin-top:4px">'+esc(m.role)+' · '+esc(m.loginName||'sin login visible')+'</div></div><span class="badge">miembro</span></div>'}
function identitySource(i){return i.pluginId||i.provider||'identidad'}
function identityRow(i,current,people){const options=people.filter(p=>p.id!==current.id).map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join('');return '<div style="padding:10px 0;border-top:1px solid var(--line)"><div class="row between"><div><div class="row"><span class="badge">'+esc(identitySource(i))+'</span><strong>'+esc(i.label||i.externalValue)+'</strong></div><div class="small muted" style="margin-top:4px">'+esc(i.kind)+' · '+esc(i.externalValue)+'</div></div>'+(options?'<select data-link-identity="'+esc(i.id)+'" data-current-person="'+esc(current.name)+'" style="width:210px"><option value="">Vincular a otra persona…</option>'+options+'</select>':'')+'</div></div>'}
function personRow(p,people){const ids=p.identities||[];return '<div class="card soft" style="margin-bottom:10px"><div class="row between"><div><strong>'+esc(p.name||'Persona')+'</strong><div class="small muted" style="margin-top:4px">'+esc(p.visibility||'contexto')+(p.ownerMemberId?' · vinculada a miembro SOL':'')+'</div></div><span class="badge">'+ids.length+' identidad'+(ids.length===1?'':'es')+'</span></div>'+(ids.length?ids.map(i=>identityRow(i,p,people)).join(''):'<div class="small muted" style="margin-top:10px">Sin identidades externas vinculadas.</div>')+'</div>'}
async function linkIdentity(identityId,currentName,targetId){if(!targetId)return;const target=state.people.find(p=>p.id===targetId);if(!target)return;if(!confirm('¿Vincular esta identidad de “'+currentName+'” con la Persona “'+target.name+'”?\n\nEsto no cambia permisos ni acceso a SOL.'))return;const out=await api('/v1/knowledge/people/'+encodeURIComponent(targetId)+'/identities/'+encodeURIComponent(identityId),{method:'POST'});if(!out.r.ok){alert(out.b.error||'No se pudo vincular la identidad');return}await loadPeople()}
function bindPeopleActions(){document.querySelectorAll('[data-link-identity]').forEach(s=>s.onchange=()=>linkIdentity(s.dataset.linkIdentity,s.dataset.currentPerson,s.value));document.querySelectorAll('[data-open-plugin="nexo"]').forEach(b=>b.onclick=()=>{const nexo=state.plugins.find(p=>String(p.manifest?.id||'').toLowerCase().includes('nexo')||String(p.manifest?.name||'').toLowerCase().includes('nexo'));const url=nexo&&pluginPanelUrl(nexo);if(url)window.open(url,'_blank','noopener');else location.href='/v1/inputs/plugins/ui'})}
async function loadPeople(){const me=await api('/v1/auth/me');if(!me.r.ok)return;const member=me.b.member||{};const [mr,pr]=await Promise.all([api('/v1/households/'+encodeURIComponent(member.householdId)+'/members'),api('/v1/knowledge/people')]);const members=mr.r.ok?mr.b.members||[]:[];state.people=pr.r.ok?pr.b.people||[]:[];document.getElementById('member-count').textContent=members.length;document.getElementById('known-count').textContent=state.people.length;document.getElementById('members').innerHTML=members.length?members.map(memberRow).join(''):'<div class="empty">Sin miembros.</div>';document.getElementById('known-people').innerHTML=state.people.length?state.people.map(p=>personRow(p,state.people)).join(''):'<div class="empty">Todavía no hay personas detectadas.</div>';bindPeopleActions()}
function setView(view,push=true){const people=view==='people';document.getElementById('connections-view').hidden=people;document.getElementById('people-view').hidden=!people;document.getElementById('tab-connections').classList.toggle('active',!people);document.getElementById('tab-people').classList.toggle('active',people);document.getElementById('page-title').textContent=people?'Personas.':'Conexiones.';document.getElementById('page-lead').textContent=people?'Una Persona canónica puede reunir WhatsApp, Home Assistant, voz y futuras identidades sin mezclar eso con permisos.':'Todo lo que vinculaste con SOL, ordenado por servicio y cuenta. Acá importa qué está conectado; los detalles de runtime quedan en Sistema.';document.querySelectorAll('.nav a').forEach(a=>a.classList.remove('active'));const nav=[...document.querySelectorAll('.nav a')].find(a=>people?a.getAttribute('href')?.includes('view=people'):a.getAttribute('href')==='/inputs');if(nav)nav.classList.add('active');if(push){const u=new URL(location.href);if(people)u.searchParams.set('view','people');else u.searchParams.delete('view');history.pushState({},'',u)}if(people)loadPeople()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));window.onpopstate=()=>setView(new URL(location.href).searchParams.get('view')==='people'?'people':'connections',false);
(async()=>{await loadConnections();setView(new URL(location.href).searchParams.get('view')==='people'?'people':'connections',false)})();
`;
  return solPage("inputs", "Conexiones", body, script);
}
