import { solPage } from "./shell.js";

export function renderInputsPage(): string {
  const body = `<section class="page">
    <div class="toolbar"><div><div class="eyebrow">SOL · Inputs</div><h1>Todo lo que entra.</h1><p class="lead">Inputs muestra las cuentas y fuentes registradas por tus servicios. La conexión con WhatsApp, Home Assistant, Google y otros proveedores se administra desde Servicios, no desde páginas duplicadas dentro de Core.</p></div><a class="button primary" href="/services">+ Agregar servicio</a></div>
    <div id="summary" class="grid" style="margin-bottom:16px"><div class="card span4"><div class="stat">—</div><div class="label">inputs</div></div><div class="card span4"><div class="stat">—</div><div class="label">ítems 24 h</div></div><div class="card span4"><div class="stat">—</div><div class="label">conectados</div></div></div>
    <section id="inputs"><div class="empty">Cargando inputs…</div></section>
  </section>
  <dialog id="modal"><div class="dialogbody"><div class="dialoghead"><div><div class="eyebrow" id="modal-eye">Input</div><h2 id="modal-title">Detalle</h2></div><button id="modal-close">✕</button></div><div id="modal-body"></div></div></dialog>`;

  const script = `
const root=document.getElementById('inputs'),summary=document.getElementById('summary'),modal=document.getElementById('modal'),modalBody=document.getElementById('modal-body');let current=[];
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
async function api(path,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(path,{cache:'no-store',...o,signal:c.signal});let b={};try{b=await r.json()}catch{}if(r.status===401){location.href='/';return{r,b}}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(t)}}
function fmt(v){if(!v)return 'Nunca';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function providerLabel(p){return({whatsapp:'WhatsApp',gmail:'Gmail',google_calendar:'Google Calendar',home_assistant:'Home Assistant',mercadolibre:'Mercado Libre'})[p]||p||'Servicio'}
function glyph(p){return({whatsapp:'W',gmail:'G',google_calendar:'C',home_assistant:'H',mercadolibre:'M'})[p]||'•'}
function stateOf(x){const s=String(x.status||'disconnected');if(s==='connected')return['good','conectado'];if(s==='error')return['bad','error'];return['','desconectado']}
function pluginManaged(x){return String(x.authMode||'').startsWith('plugin:')}
function card(x){const [dot,state]=stateOf(x),st=x.stats||{},last=st.lastObservedAt||st.lastItemAt||x.lastSyncAt,managed=pluginManaged(x);return '<article class="card" style="margin-bottom:12px"><div class="row between"><div class="cluster"><div style="width:38px;height:38px;border-radius:12px;background:#202632;display:grid;place-items:center;font-weight:900">'+esc(glyph(x.provider))+'</div><div><h2>'+esc(x.label)+'</h2><div class="muted small">'+esc(providerLabel(x.provider))+' · '+(x.shared?'familiar':'personal')+(x.externalAccountId?' · '+esc(x.externalAccountId):'')+'</div></div></div><span class="badge"><span class="dot '+dot+'"></span>'+esc(state)+'</span></div><div class="grid" style="margin-top:16px"><div class="span4"><div class="stat" style="font-size:22px">'+Number(st.totalItems||0).toLocaleString('es-AR')+'</div><div class="label">ítems en SOL</div></div><div class="span4"><div class="stat" style="font-size:22px">'+Number(st.items24h||0).toLocaleString('es-AR')+'</div><div class="label">últimas 24 h</div></div><div class="span4"><div class="stat" style="font-size:15px;margin-top:4px">'+esc(fmt(last))+'</div><div class="label">último dato</div></div></div><div class="cluster" style="margin-top:16px"><button data-feed="'+esc(x.id)+'">Ver feed</button>'+(x.canManage?'<button data-edit="'+esc(x.id)+'">Editar</button>':'')+(managed?'<a class="button" href="/services">Administrar servicio</a>':x.canManage?'<button class="danger" data-remove="'+esc(x.id)+'">Eliminar</button>':'')+'</div>'+(managed?'<div class="small muted" style="margin-top:10px">Esta cuenta pertenece a un plugin. Vinculación, credenciales y eliminación se gestionan desde Servicios.</div>':'')+'</article>'}
async function load(){const out=await api('/v1/inputs');if(!out.r.ok){root.innerHTML='<div class="empty error">'+esc(out.b.error||'No se pudieron cargar los inputs')+'</div>';return}current=out.b.inputs||[];const total24=current.reduce((n,x)=>n+Number(x.stats?.items24h||0),0),connected=current.filter(x=>x.status==='connected').length;summary.innerHTML='<div class="card span4"><div class="stat">'+current.length+'</div><div class="label">inputs visibles</div></div><div class="card span4"><div class="stat">'+total24.toLocaleString('es-AR')+'</div><div class="label">ítems recibidos en 24 h</div></div><div class="card span4"><div class="stat">'+connected+'/'+current.length+'</div><div class="label">conectados</div></div>';root.innerHTML=current.length?current.map(card).join(''):'<div class="empty">Todavía no hay inputs. <a href="/services">Instalá o configurá un servicio</a> para empezar.</div>';bind()}
function openDialog(title,html,eye='Input'){document.getElementById('modal-title').textContent=title;document.getElementById('modal-eye').textContent=eye;modalBody.innerHTML=html;modal.showModal()}
document.getElementById('modal-close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
function bind(){document.querySelectorAll('[data-feed]').forEach(b=>b.onclick=()=>showFeed(b.dataset.feed));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>showEdit(b.dataset.edit));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeInput(b.dataset.remove))}
async function showFeed(id){const x=current.find(v=>v.id===id);openDialog('Feed · '+(x?.label||''),'<div class="empty">Cargando registros…</div>','Datos recibidos');const out=await api('/v1/inputs/'+encodeURIComponent(id)+'/items?limit=100');if(!out.r.ok){modalBody.innerHTML='<div class="empty error">'+esc(out.b.error||'Error')+'</div>';return}const items=out.b.items||[];modalBody.innerHTML=items.length?'<div class="feed">'+items.map(i=>'<div class="feeditem"><div class="row between"><strong>'+esc(i.metadata?.pushName||i.metadata?.from||i.title||i.kind)+'</strong><span class="small muted">'+esc(fmt(i.occurredAt))+'</span></div>'+(i.text?'<div class="feedtext">'+esc(i.text)+'</div>':'')+'<div class="small muted" style="margin-top:5px">'+esc(i.kind)+'</div></div>').join('')+'</div>':'<div class="empty">Este input todavía no recibió ítems.</div>'}
function showEdit(id){const x=current.find(v=>v.id===id);if(!x)return;openDialog('Editar '+x.label,'<form id="edit-form"><label>Nombre<input name="label" value="'+esc(x.label)+'" required maxlength="160"></label><label style="margin-top:10px">Visibilidad<select name="shared"><option value="false"'+(!x.shared?' selected':'')+'>Personal</option><option value="true"'+(x.shared?' selected':'')+'>Familiar</option></select></label><div class="cluster" style="margin-top:14px"><button class="primary">Guardar</button><span id="edit-status" class="muted"></span></div></form>','Input');document.getElementById('edit-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget).entries()),st=document.getElementById('edit-status');st.textContent='Guardando…';const out=await api('/v1/inputs/'+encodeURIComponent(id),{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({label:d.label,shared:d.shared==='true'})});if(!out.r.ok){st.className='error';st.textContent=out.b.error||'No se pudo guardar';return}modal.close();await load()}}
async function removeInput(id){const x=current.find(v=>v.id===id);if(!confirm('¿Eliminar '+(x?.label||'este input')+'?'))return;const out=await api('/v1/inputs/'+encodeURIComponent(id),{method:'DELETE'});if(!out.r.ok){alert(out.b.hint||out.b.error||'No se pudo eliminar');return}await load()}
load();setInterval(()=>{if(!document.hidden)load().catch(()=>{})},15000);
`;
  return solPage("inputs", "Inputs", body, script);
}
