import { solPage } from "./shell.js";

export function renderLifePage(): string {
  const body = `<section class="page">
    <div class="eyebrow">SOL · Life</div><h1>Todo lo que entró.</h1><p class="lead">Life es el registro cronológico real. Acá aparecen mensajes, correos y demás observaciones aunque todavía no hayan sido convertidos en Knowledge.</p>
    <div class="toolbar" style="margin-bottom:16px"><div class="seg" id="tabs"><button class="active" data-tab="timeline">Timeline</button><button data-tab="people">Personas</button><button data-tab="projects">Proyectos</button></div><div class="cluster"><span class="badge" id="live-badge"><span class="dot good"></span>actualización automática</span><a class="button" href="/inputs">Administrar inputs</a></div></div>
    <section id="timeline-tools" class="card" style="margin-bottom:14px"><div class="toolbar"><div class="cluster" id="providers"><button class="active" data-provider="all">Todo</button><button data-provider="whatsapp">WhatsApp</button><button data-provider="gmail">Gmail</button><button data-provider="google_calendar">Calendar</button><button data-provider="home_assistant">Home Assistant</button><button data-provider="mercadolibre">Mercado Libre</button><button data-provider="mcp">MCP</button></div><input id="search" placeholder="Buscar en lo cargado…" style="max-width:260px"></div></section>
    <section id="content"><div class="empty">Cargando Life…</div></section>
  </section>`;

  const script = `
const content=document.getElementById('content'),tools=document.getElementById('timeline-tools'),search=document.getElementById('search');let current='timeline',provider='all',nextBefore,items=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function api(path,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(path,{cache:'no-store',...o,signal:c.signal});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(t)}}
function when(v){try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function vis(v){return({private:'privado',family:'familia',shared:'compartido',project:'proyecto',system:'sistema'})[v]||v}
function pname(p){return({whatsapp:'WhatsApp',gmail:'Gmail',google_calendar:'Calendar',home_assistant:'Home Assistant',mercadolibre:'Mercado Libre',mcp:'MCP'})[p]||p||'SOL'}
function glyph(i){if(i.type==='task')return '✓';if(i.type==='event')return '◷';return({whatsapp:'W',gmail:'G',google_calendar:'C',home_assistant:'H',mercadolibre:'M',mcp:'S'})[i.provider]||'•'}
function filtered(){const q=search.value.trim().toLowerCase();return items.filter(i=>(provider==='all'||i.provider===provider)&&(!q||[i.title,i.summary,i.sourceLabel,pname(i.provider)].some(v=>String(v||'').toLowerCase().includes(q))))}
function card(i){return '<article class="card" style="margin-bottom:9px"><div class="row between"><div class="cluster"><div style="width:34px;height:34px;border-radius:10px;background:#202632;display:grid;place-items:center;font-weight:900">'+esc(glyph(i))+'</div><div><h2>'+esc(i.title)+'</h2><div class="small muted">'+esc(pname(i.provider))+(i.sourceLabel?' · '+esc(i.sourceLabel):'')+'</div></div></div><span class="small muted">'+esc(when(i.occurredAt))+'</span></div>'+(i.summary?'<div style="white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.5;margin:12px 0 2px">'+esc(i.summary)+'</div>':'')+'<div class="cluster" style="margin-top:10px"><span class="badge">'+esc(i.type)+'</span><span class="badge">'+esc(vis(i.visibility))+'</span>'+(i.metadata?.candidateScore!==undefined?'<span class="badge">score '+esc(i.metadata.candidateScore)+'</span>':'')+'</div></article>'}
function renderTimeline(){const list=filtered();content.innerHTML=list.length?list.map(card).join(''):'<div class="empty">No hay elementos con este filtro. Abrí <a href="/inputs">Inputs</a> para verificar el feed crudo y el estado de esa fuente.</div>';if(nextBefore&&provider==='all'&&!search.value.trim()){content.insertAdjacentHTML('beforeend','<button id="more" style="margin-top:12px">Cargar anteriores</button>');document.getElementById('more').onclick=()=>loadTimeline(true)}}
async function loadTimeline(append=false,silent=false){if(!append&&!silent)content.innerHTML='<div class="empty">Cargando timeline…</div>';const q=new URLSearchParams({limit:'80'});if(append&&nextBefore)q.set('before',nextBefore);const out=await api('/v1/life/timeline?'+q);if(!out.r.ok){if(!silent)content.innerHTML='<div class="empty error">'+esc(out.b.error||'No se pudo cargar')+'</div>';return}if(append)items.push(...(out.b.items||[]));else items=out.b.items||[];nextBefore=out.b.nextBefore;renderTimeline()}
function val(v){if(v===undefined||v===null)return '';if(typeof v==='string')return v;try{return JSON.stringify(v)}catch{return String(v)}}
function entityCard(e){const facts=(e.facts||[]).map(f=>'<div class="feeditem"><strong>'+esc(f.predicate)+'</strong><div class="small" style="margin-top:4px">'+esc(val(f.value)||f.objectEntityId||'—')+'</div></div>').join('');return '<article class="card"><div class="row between"><h2>'+esc(e.name)+'</h2><span class="badge">'+esc(vis(e.visibility))+'</span></div>'+(e.aliases?.length?'<div class="small muted" style="margin-top:5px">También: '+esc(e.aliases.join(', '))+'</div>':'')+'<div class="divider"></div>'+(facts||'<div class="muted small">Sin hechos consolidados todavía.</div>')+'</article>'}
async function loadEntities(kind){content.innerHTML='<div class="empty">Cargando…</div>';const out=await api('/v1/knowledge/entities?kind='+kind);if(!out.r.ok){content.innerHTML='<div class="empty error">'+esc(out.b.error||'Error')+'</div>';return}const list=out.b.entities||[];content.innerHTML='<div class="toolbar" style="margin-bottom:12px"><span class="muted">'+list.length+' '+(kind==='person'?'persona(s)':'proyecto(s)')+'</span><button class="primary" id="create">+ '+(kind==='person'?'Persona':'Proyecto')+'</button></div>'+(list.length?'<div class="grid">'+list.map(e=>'<div class="span6">'+entityCard(e)+'</div>').join('')+'</div>':'<div class="empty">Todavía no hay '+(kind==='person'?'personas':'proyectos')+' visibles.</div>');document.getElementById('create').onclick=()=>createEntity(kind)}
async function createEntity(kind){const name=prompt('Nombre:');if(!name?.trim())return;const family=confirm('¿Visible para la familia?\\nAceptar = familia · Cancelar = privado');const out=await api('/v1/knowledge/entities',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kind,name:name.trim(),visibility:family?'family':'private'})});if(!out.r.ok){alert(out.b.error||'No se pudo crear');return}await loadEntities(kind)}
async function select(tab){current=tab;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));tools.style.display=tab==='timeline'?'block':'none';if(tab==='timeline')await loadTimeline();else await loadEntities(tab==='people'?'person':'project')}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>select(b.dataset.tab));document.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{provider=b.dataset.provider;document.querySelectorAll('[data-provider]').forEach(x=>x.classList.toggle('active',x===b));renderTimeline()});search.oninput=()=>renderTimeline();
select('timeline');setInterval(()=>{if(current==='timeline'&&!document.hidden)loadTimeline(false,true).catch(()=>{})},10000);
`;
  return solPage("life", "Life", body, script);
}
