import { solPage } from "./shell.js";

export function renderMcpPage(): string {
  const body = `<section class="page">
    <div class="eyebrow">SOL · MCP</div>
    <h1>Conectar ChatGPT, Codex y otros clientes a SOL.</h1>
    <p class="lead">SOL expone memoria, Life y las herramientas registradas por sus plugins mediante un acceso MCP por miembro. Home Assistant, Nexo y futuras integraciones siguen detrás de SOL: el cliente nunca recibe sus credenciales.</p>
    <section id="app"><div class="empty">Cargando MCP…</div></section>
  </section>`;

  const script = `
const app=document.getElementById('app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
async function api(path,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(path,{cache:'no-store',...o,signal:c.signal});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(t)}}
function fmt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function winPath(v){const bs=String.fromCharCode(92);return String(v||'').split(bs).join('/').split('/').join(bs)}
function launcherPath(status){return winPath(status.repoRoot)+'\\\\'+winPath(status.portableCommand||'scripts/windows/sol-mcp.ps1')}
function codexConfigText(status,token){return JSON.stringify({mcpServers:{sol:{command:'powershell.exe',args:['-NoProfile','-ExecutionPolicy','Bypass','-File',launcherPath(status)],env:{SOL_MCP_TOKEN:token}}}},null,2)}
function tunnelText(status,token){const launcher=launcherPath(status).replace(/"/g,'');return '$env:CONTROL_PLANE_API_KEY="<OPENAI_PLATFORM_API_KEY>"\\n'+'$env:SOL_MCP_TOKEN="'+token+'"\\n'+'tunnel-client init --sample sample_mcp_stdio_local --profile sol-chatgpt --tunnel-id "<TUNNEL_ID>" --mcp-command "powershell.exe -NoProfile -ExecutionPolicy Bypass -File \`"'+launcher+'\`""\\n'+'tunnel-client doctor --profile sol-chatgpt --explain\\n'+'tunnel-client run --profile sol-chatgpt'}
function tokenRow(t){const scopes=(t.scopes||[]).map(s=>'<span class="badge">'+esc(s)+'</span>').join(' ');return '<div class="feeditem"><div class="row between"><div><strong>'+esc(t.label)+'</strong><div class="small muted" style="margin-top:4px">Creado '+esc(fmt(t.createdAt))+' · vence '+esc(fmt(t.expiresAt))+(t.lastUsedAt?' · usado '+esc(fmt(t.lastUsedAt)):'')+'</div><div class="cluster" style="margin-top:7px">'+scopes+'</div></div>'+(t.revokedAt?'<span class="badge">revocado</span>':'<button class="danger revoke" data-id="'+esc(t.id)+'">Revocar</button>')+'</div></div>'}
async function load(){const [me,s,t]=await Promise.all([api('/v1/auth/me'),api('/v1/mcp/status'),api('/v1/mcp/tokens')]);if(!me.r.ok){app.innerHTML='<div class="empty">Necesitás iniciar sesión. <a href="/">Volver</a></div>';return}if(!s.r.ok||!t.r.ok){app.innerHTML='<div class="empty error">'+esc(s.b.error||t.b.error||'No se pudo cargar MCP')+'</div>';return}render(me.b.member,s.b,t.b.tokens||[])}
function render(me,status,tokens){
const canActions=me.role==='owner'||me.role==='adult';
const actionsGrant=canActions?'<label style="display:flex;align-items:center;gap:8px;margin-top:12px;color:var(--text)"><input name="allowActions" type="checkbox" style="width:auto"> Permitir acciones externas confirmadas (Home Assistant y otras tools de plugins)</label><p class="small muted">El scope <code>actions</code> habilita tools de acción. Las tools que lo exijan siguen requiriendo confirmación explícita del usuario.</p>':'<p class="small muted">Sólo owner/adult puede generar tokens con scope <code>actions</code>.</p>';
app.innerHTML='<div class="grid">'+
'<div class="card span12"><div class="row between"><div><h2>SOL MCP</h2><div class="small muted" style="margin-top:5px">'+esc(me.displayName)+' · '+esc(me.role)+' · '+esc(status.protocol)+'</div></div><span class="badge"><span class="dot good"></span>ChatGPT tunnel ready</span></div>'+
'<div class="cluster" style="margin-top:14px">'+(status.tools||[]).map(x=>'<span class="badge">'+esc(x)+'</span>').join('')+'</div>'+
'<p class="muted small" style="line-height:1.55">El bridge usa MCP por <code>stdio</code>. Para ChatGPT remoto, Secure MCP Tunnel lanza este mismo servidor local mediante una conexión HTTPS saliente: no hace falta publicar SOL ni Home Assistant en Internet.</p>'+
'<div class="divider"></div><div class="grid"><div class="span4"><strong>ChatGPT / Voice</strong><div class="small muted">Interpreta la consulta y elige tools disponibles.</div></div><div class="span4"><strong>SOL autoriza</strong><div class="small muted">Identidad, scopes, privacidad, memoria y Tool Registry.</div></div><div class="span4"><strong>Plugins ejecutan</strong><div class="small muted">Home Assistant, Nexo y demás proveedores conservan sus credenciales.</div></div></div></div>'+
'<div class="card span6"><h2>Crear acceso para ChatGPT</h2><form id="create" style="margin-top:14px"><label>Nombre del cliente<input name="label" value="ChatGPT · SOL" maxlength="120" required></label><label style="margin-top:10px">Vence en<select name="days"><option value="30">30 días</option><option value="90" selected>90 días</option><option value="180">180 días</option><option value="365">365 días</option></select></label><label style="display:flex;align-items:center;gap:8px;margin-top:12px;color:var(--text)"><input name="allowSubmit" type="checkbox" style="width:auto"> Permitir memoria/observaciones confirmadas</label><p class="small muted">Lectura está incluida. <code>submit</code> permite guardar sólo contenido confirmado por la persona autenticada.</p>'+actionsGrant+'<div class="cluster"><button class="primary">Generar token</button><span id="create-status" class="muted small"></span></div></form><div id="secret"></div></div>'+
'<div class="card span6"><h2>Accesos creados</h2><div class="divider"></div><div id="tokens">'+(tokens.length?tokens.map(tokenRow).join(''):'<div class="empty">Todavía no hay tokens MCP.</div>')+'</div></div>'+
'<div class="card span12"><h2>Cómo llega ChatGPT a SOL</h2><div class="grid" style="margin-top:12px"><div class="span3"><strong>1 · SOL</strong><div class="small muted">Queda local en tu PC.</div></div><div class="span3"><strong>2 · Bridge</strong><div class="small muted"><code>sol-mcp.ps1</code> inicia el MCP portable.</div></div><div class="span3"><strong>3 · Tunnel</strong><div class="small muted">Secure MCP Tunnel conecta hacia OpenAI.</div></div><div class="span3"><strong>4 · ChatGPT</strong><div class="small muted">La app SOL ve tools según los scopes del token.</div></div></div><p class="small muted" style="margin-top:12px">La disponibilidad de apps MCP personalizadas y acciones depende del plan/superficie de ChatGPT. El bridge de SOL queda preparado independientemente de esa habilitación.</p></div>'+
'</div>';
const form=document.getElementById('create');
form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),slot=document.getElementById('secret'),st=document.getElementById('create-status');st.textContent='Generando…';const out=await api('/v1/mcp/tokens',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:fd.get('label'),expiresInDays:Number(fd.get('days')),allowSubmit:fd.get('allowSubmit')==='on',allowActions:fd.get('allowActions')==='on'})});if(!out.r.ok){st.className='error small';st.textContent=out.b.error||'No se pudo crear';return}st.textContent='';const codex=codexConfigText(status,out.b.token),tunnel=tunnelText(status,out.b.token);slot.innerHTML='<div class="card soft" style="margin-top:14px;border-color:var(--warn)"><strong>Copialo ahora: SOL guarda sólo el hash del token.</strong><div class="cluster" style="margin-top:8px">'+(out.b.access.scopes||[]).map(s=>'<span class="badge">'+esc(s)+'</span>').join('')+'</div><pre id="token-value" style="white-space:pre-wrap;overflow-wrap:anywhere;background:#0d1015;padding:12px;border-radius:11px">'+esc(out.b.token)+'</pre><div class="cluster"><button type="button" id="copy-token">Copiar token</button><button type="button" id="copy-tunnel">Copiar comando Tunnel</button><button type="button" id="copy-config">Copiar config MCP</button></div><div class="small muted" style="margin-top:12px">Secure MCP Tunnel (reemplazá &lt;OPENAI_PLATFORM_API_KEY&gt; y &lt;TUNNEL_ID&gt;)</div><pre id="tunnel-value" style="white-space:pre-wrap;overflow-wrap:anywhere;background:#0d1015;padding:12px;border-radius:11px">'+esc(tunnel)+'</pre><div class="small muted" style="margin-top:12px">Cliente MCP local / Codex</div><pre id="config-value" style="white-space:pre-wrap;overflow-wrap:anywhere;background:#0d1015;padding:12px;border-radius:11px">'+esc(codex)+'</pre></div>';document.getElementById('copy-token').onclick=()=>navigator.clipboard.writeText(out.b.token);document.getElementById('copy-tunnel').onclick=()=>navigator.clipboard.writeText(tunnel);document.getElementById('copy-config').onclick=()=>navigator.clipboard.writeText(codex);await refreshTokens()};
bindRevokes()
}
function bindRevokes(){document.querySelectorAll('.revoke').forEach(b=>b.onclick=async()=>{if(!confirm('¿Revocar este acceso MCP?'))return;b.disabled=true;await api('/v1/mcp/tokens/'+encodeURIComponent(b.dataset.id),{method:'DELETE'});await refreshTokens()})}
async function refreshTokens(){const out=await api('/v1/mcp/tokens');if(!out.r.ok)return;const slot=document.getElementById('tokens');slot.innerHTML=(out.b.tokens||[]).length?(out.b.tokens||[]).map(tokenRow).join(''):'<div class="empty">Todavía no hay tokens MCP.</div>';bindRevokes()}
load().catch(error=>{app.innerHTML='<div class="empty error">Error MCP: '+esc(error?.message||error)+'</div>'});
`;
  return solPage("mcp", "MCP", body, script);
}
