export function renderMcpPage(): string {
  return `<!doctype html>
<html lang="es"><head>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>SOL · MCP</title>
<style>
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText}main{width:min(980px,calc(100% - 28px));margin:auto;padding:38px 0 80px}.top,.row,.actions{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.top,.row{justify-content:space-between}.brand{font-size:13px;font-weight:900;letter-spacing:.17em;opacity:.65}nav{display:flex;gap:14px;flex-wrap:wrap;font-size:14px}a{color:inherit}h1{font-size:clamp(38px,7vw,64px);letter-spacing:-.05em;margin:15px 0 7px}h2{margin:0 0 8px}.muted{opacity:.63}p{line-height:1.55}.card{padding:20px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:19px;margin:14px 0}.pill{font-size:12px;padding:5px 9px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);border-radius:999px}.grid{display:grid;grid-template-columns:1fr 160px;gap:12px}label{display:grid;gap:6px;font-size:13px;font-weight:700}label.check{display:flex;align-items:center;gap:9px;font-weight:600;margin-top:13px}label.check input{width:auto}input,select{padding:11px 12px;border-radius:11px;border:1px solid color-mix(in srgb,CanvasText 20%,transparent);background:Canvas;color:CanvasText;font:inherit}button{padding:10px 14px;border-radius:999px;border:0;background:CanvasText;color:Canvas;font:inherit;font-weight:800;cursor:pointer}button.secondary{background:transparent;color:CanvasText;border:1px solid color-mix(in srgb,CanvasText 20%,transparent)}button.danger{background:transparent;color:#d33;border:1px solid color-mix(in srgb,#d33 45%,transparent)}button:disabled{opacity:.45}pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:14px;border-radius:14px;background:color-mix(in srgb,CanvasText 7%,transparent);font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace}.error{color:#d33}.token{padding:12px 0;border-top:1px solid color-mix(in srgb,CanvasText 9%,transparent)}.token:first-child{border-top:0}.secret{border:1px solid color-mix(in srgb,#c28b00 45%,transparent);padding:16px;border-radius:14px;margin:14px 0}.tools{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}@media(max-width:680px){.grid{grid-template-columns:1fr}.top{align-items:flex-start}}
</style></head><body><main>
<div class="top"><div class="brand">SOL · MCP</div><nav><a href="/">Inicio</a><a href="/life">Vida</a><a href="/ai">AI opcional</a></nav></div>
<h1>SOL como memoria.</h1>
<p class="muted">MCP expone Life, Knowledge, Home Assistant y negocio a clientes autorizados. Cada token representa exactamente a un miembro. El scope opcional <code>submit</code> permite aportar información a Life, pero nunca ejecutar acciones externas ni escribir Knowledge sin provenance.</p>
<section id="app"><p class="muted">Cargando MCP…</p></section>
</main><script>
const app=document.getElementById('app');
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
async function api(path,o={}){const r=await fetch(path,{cache:'no-store',...o});let b={};try{b=await r.json()}catch{}return{r,b}}
function fmt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function configText(status,token){return JSON.stringify({mcpServers:{sol:{command:'pnpm',args:['--dir',status.repoRoot,'mcp'],env:{SOL_MCP_TOKEN:token}}}},null,2)}
function tokenRow(t){const scopes=(t.scopes||[]).map(s=>'<span class="pill">'+esc(s)+'</span>').join(' ');return '<div class="token"><div class="row"><div><strong>'+esc(t.label)+'</strong><div class="muted">Creado '+esc(fmt(t.createdAt))+' · vence '+esc(fmt(t.expiresAt))+(t.lastUsedAt?' · usado '+esc(fmt(t.lastUsedAt)):'')+'</div><div class="tools">'+scopes+'</div></div>'+(t.revokedAt?'<span class="pill">revocado</span>':'<button class="danger revoke" data-id="'+esc(t.id)+'">Revocar</button>')+'</div></div>'}
async function load(){const [me,s,t]=await Promise.all([api('/v1/auth/me'),api('/v1/mcp/status'),api('/v1/mcp/tokens')]);if(!me.r.ok){app.innerHTML='<div class="card"><h2>Necesitás iniciar sesión</h2><a href="/">Volver</a></div>';return}if(!s.r.ok||!t.r.ok){app.innerHTML='<div class="card"><h2>No se pudo cargar MCP</h2><p class="error">'+esc(s.b.error||t.b.error||'Error')+'</p></div>';return}render(me.b.member,s.b,t.b.tokens||[])}
function render(me,status,tokens){app.innerHTML='<div class="card"><div class="row"><div><h2>Servidor MCP local</h2><div class="muted">'+esc(me.displayName)+' · '+esc(me.role)+' · '+esc(status.protocol)+'</div></div><span class="pill">'+esc(status.mode)+'</span></div><div class="tools">'+(status.tools||[]).map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</div><p>El cliente lanza <code>pnpm mcp</code> desde este repo. SOL valida el token antes de exponer información o aceptar aportes.</p></div><div class="card"><h2>Crear acceso MCP</h2><form id="create"><div class="grid"><label>Nombre del cliente<input name="label" value="Mi cliente MCP" maxlength="120" required></label><label>Vence en<select name="days"><option value="30">30 días</option><option value="90" selected>90 días</option><option value="180">180 días</option><option value="365">365 días</option></select></label></div><label class="check"><input name="allowSubmit" type="checkbox"> Permitir que este cliente aporte información y horarios a SOL</label><p class="muted">Esto agrega el scope <code>submit</code>. Sólo crea observaciones con provenance en Life; no permite Calendar, Home Assistant, Mercado Libre ni otras acciones externas.</p><div class="actions" style="margin-top:12px"><button>Generar token</button><span id="create-status" class="muted"></span></div></form><div id="secret"></div></div><div class="card"><h2>Accesos creados</h2><div id="tokens">'+(tokens.length?tokens.map(tokenRow).join(''):'<p class="muted">Todavía no hay tokens MCP.</p>')+'</div></div>';
const form=document.getElementById('create');form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),slot=document.getElementById('secret'),st=document.getElementById('create-status');st.textContent='Generando…';const out=await api('/v1/mcp/tokens',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:fd.get('label'),expiresInDays:Number(fd.get('days')),allowSubmit:fd.get('allowSubmit')==='on'})});if(!out.r.ok){st.className='error';st.textContent=out.b.error||'No se pudo crear';return}st.textContent='';const conf=configText(status,out.b.token);slot.innerHTML='<div class="secret"><strong>Copialo ahora: SOL no guarda el token original.</strong><div class="tools">'+(out.b.access.scopes||[]).map(s=>'<span class="pill">'+esc(s)+'</span>').join('')+'</div><pre id="token-value">'+esc(out.b.token)+'</pre><div class="actions"><button type="button" class="secondary" id="copy-token">Copiar token</button><button type="button" class="secondary" id="copy-config">Copiar config MCP</button></div><p class="muted">Plantilla genérica:</p><pre id="config-value">'+esc(conf)+'</pre></div>';document.getElementById('copy-token').onclick=()=>navigator.clipboard.writeText(out.b.token);document.getElementById('copy-config').onclick=()=>navigator.clipboard.writeText(conf);await refreshTokens()};
document.querySelectorAll('.revoke').forEach(b=>b.onclick=async()=>{if(!confirm('¿Revocar este acceso MCP?'))return;b.disabled=true;await api('/v1/mcp/tokens/'+encodeURIComponent(b.dataset.id),{method:'DELETE'});await refreshTokens()})}
async function refreshTokens(){const out=await api('/v1/mcp/tokens');if(!out.r.ok)return;const slot=document.getElementById('tokens');slot.innerHTML=(out.b.tokens||[]).length?(out.b.tokens||[]).map(tokenRow).join(''):'<p class="muted">Todavía no hay tokens MCP.</p>';document.querySelectorAll('.revoke').forEach(b=>b.onclick=async()=>{if(!confirm('¿Revocar este acceso MCP?'))return;b.disabled=true;await api('/v1/mcp/tokens/'+encodeURIComponent(b.dataset.id),{method:'DELETE'});await refreshTokens()})}
load().catch(error=>{app.innerHTML='<div class="card"><h2>Error MCP</h2><p class="error">'+esc(error?.message||error)+'</p></div>'});
</script></body></html>`;
}
