import { solPage } from "./shell.js";

export function renderMcpPage(): string {
  const body = `<section class="page">
    <div class="eyebrow">Nexo · MCP</div>
    <h1>Darle memoria a Codex.</h1>
    <p class="lead">Nexo no intenta ser el asistente. Este MCP le da a Codex acceso autorizado a WhatsApp, Life y memoria familiar/personal. Gmail, Calendar y Home Assistant se conectan directamente a Codex por sus propias herramientas.</p>
    <section id="app"><div class="empty">Cargando MCP…</div></section>
  </section>`;

  const script = `
const app=document.getElementById('app');
function esc(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]))}
async function api(path,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(path,{cache:'no-store',...o,signal:c.signal});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(t)}}
function fmt(v){if(!v)return '—';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
function configText(status,token){return JSON.stringify({mcpServers:{nexo:{command:'pnpm',args:['--dir',status.repoRoot,'mcp'],env:{NEXO_MCP_TOKEN:token}}}},null,2)}
function tokenRow(t){const scopes=(t.scopes||[]).map(s=>'<span class="badge">'+esc(s)+'</span>').join(' ');return '<div class="feeditem"><div class="row between"><div><strong>'+esc(t.label)+'</strong><div class="small muted" style="margin-top:4px">Creado '+esc(fmt(t.createdAt))+' · vence '+esc(fmt(t.expiresAt))+(t.lastUsedAt?' · usado '+esc(fmt(t.lastUsedAt)):'')+'</div><div class="cluster" style="margin-top:7px">'+scopes+'</div></div>'+(t.revokedAt?'<span class="badge">revocado</span>':'<button class="danger revoke" data-id="'+esc(t.id)+'">Revocar</button>')+'</div></div>'}
async function load(){const [me,s,t]=await Promise.all([api('/v1/auth/me'),api('/v1/mcp/status'),api('/v1/mcp/tokens')]);if(!me.r.ok){app.innerHTML='<div class="empty">Necesitás iniciar sesión. <a href="/">Volver</a></div>';return}if(!s.r.ok||!t.r.ok){app.innerHTML='<div class="empty error">'+esc(s.b.error||t.b.error||'No se pudo cargar MCP')+'</div>';return}render(me.b.member,s.b,t.b.tokens||[])}
function render(me,status,tokens){app.innerHTML='<div class="grid"><div class="card span12"><div class="row between"><div><h2>Nexo MCP local</h2><div class="small muted" style="margin-top:5px">'+esc(me.displayName)+' · '+esc(me.role)+' · '+esc(status.protocol)+'</div></div><span class="badge"><span class="dot good"></span>Codex complement</span></div><div class="cluster" style="margin-top:14px">'+(status.tools||[]).map(x=>'<span class="badge">'+esc(x)+'</span>').join('')+'</div><p class="muted small" style="line-height:1.55">El cliente lanza <code>pnpm mcp</code> desde este repo. El MCP por defecto ya es Nexo. El servidor MCP anterior se conserva temporalmente como <code>pnpm mcp:legacy</code>.</p><div class="divider"></div><div class="grid"><div class="span6"><strong>Codex piensa</strong><div class="small muted">Interpreta preguntas, cruza Gmail/Calendar/HA con Nexo y decide qué herramientas usar.</div></div><div class="span6"><strong>Nexo recuerda</strong><div class="small muted">WhatsApp, Life, personas, proyectos, memoria durable, privacidad y provenance.</div></div></div></div><div class="card span6"><h2>Crear acceso MCP</h2><form id="create" style="margin-top:14px"><label>Nombre del cliente<input name="label" value="Codex · Nexo" maxlength="120" required></label><label style="margin-top:10px">Vence en<select name="days"><option value="30">30 días</option><option value="90" selected>90 días</option><option value="180">180 días</option><option value="365">365 días</option></select></label><label style="display:flex;align-items:center;gap:8px;margin-top:12px;color:var(--text)"><input name="allowSubmit" type="checkbox" style="width:auto"> Permitir que Codex guarde observaciones/memoria confirmada</label><p class="small muted">El scope <code>submit</code> permite <code>save_observation</code>, <code>remember_fact</code> y <code>save_schedule</code>. Nunca habilita acciones externas.</p><div class="cluster"><button class="primary">Generar token</button><span id="create-status" class="muted small"></span></div></form><div id="secret"></div></div><div class="card span6"><h2>Accesos creados</h2><div class="divider"></div><div id="tokens">'+(tokens.length?tokens.map(tokenRow).join(''):'<div class="empty">Todavía no hay tokens MCP.</div>')+'</div></div></div>';
const form=document.getElementById('create');form.onsubmit=async e=>{e.preventDefault();const fd=new FormData(form),slot=document.getElementById('secret'),st=document.getElementById('create-status');st.textContent='Generando…';const out=await api('/v1/mcp/tokens',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:fd.get('label'),expiresInDays:Number(fd.get('days')),allowSubmit:fd.get('allowSubmit')==='on'})});if(!out.r.ok){st.className='error small';st.textContent=out.b.error||'No se pudo crear';return}st.textContent='';const conf=configText(status,out.b.token);slot.innerHTML='<div class="card soft" style="margin-top:14px;border-color:var(--warn)"><strong>Copialo ahora: Nexo no guarda el token original.</strong><div class="cluster" style="margin-top:8px">'+(out.b.access.scopes||[]).map(s=>'<span class="badge">'+esc(s)+'</span>').join('')+'</div><pre id="token-value" style="white-space:pre-wrap;overflow-wrap:anywhere;background:#0d1015;padding:12px;border-radius:11px">'+esc(out.b.token)+'</pre><div class="cluster"><button type="button" id="copy-token">Copiar token</button><button type="button" id="copy-config">Copiar config MCP</button></div><div class="small muted" style="margin-top:12px">Configuración para Codex</div><pre id="config-value" style="white-space:pre-wrap;overflow-wrap:anywhere;background:#0d1015;padding:12px;border-radius:11px">'+esc(conf)+'</pre></div>';document.getElementById('copy-token').onclick=()=>navigator.clipboard.writeText(out.b.token);document.getElementById('copy-config').onclick=()=>navigator.clipboard.writeText(conf);await refreshTokens()};bindRevokes()}
function bindRevokes(){document.querySelectorAll('.revoke').forEach(b=>b.onclick=async()=>{if(!confirm('¿Revocar este acceso MCP?'))return;b.disabled=true;await api('/v1/mcp/tokens/'+encodeURIComponent(b.dataset.id),{method:'DELETE'});await refreshTokens()})}
async function refreshTokens(){const out=await api('/v1/mcp/tokens');if(!out.r.ok)return;const slot=document.getElementById('tokens');slot.innerHTML=(out.b.tokens||[]).length?(out.b.tokens||[]).map(tokenRow).join(''):'<div class="empty">Todavía no hay tokens MCP.</div>';bindRevokes()}
load().catch(error=>{app.innerHTML='<div class="empty error">Error MCP: '+esc(error?.message||error)+'</div>'});
`;
  return solPage("mcp", "MCP", body, script);
}
