export function renderMercadoLibrePage(): string {
  return `<!doctype html>
<html lang="es"><head>
<meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>SOL · Mercado Libre</title>
<style>
:root{color-scheme:light dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;background:Canvas;color:CanvasText}main{width:min(1000px,calc(100% - 28px));margin:auto;padding:38px 0 80px}.top,.row,.actions,.stats{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.top,.row{justify-content:space-between}.brand{font-size:13px;font-weight:900;letter-spacing:.17em;opacity:.65}nav{display:flex;gap:14px;flex-wrap:wrap;font-size:14px}a{color:inherit}h1{font-size:clamp(38px,7vw,64px);letter-spacing:-.05em;margin:15px 0 7px}h2,h3{margin:0 0 8px}.muted{opacity:.63}p{line-height:1.55}.card{padding:20px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);border-radius:19px;margin:14px 0}.pill{font-size:12px;padding:5px 9px;border:1px solid color-mix(in srgb,CanvasText 18%,transparent);border-radius:999px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}label{display:grid;gap:6px;font-size:13px;font-weight:700}input{padding:11px 12px;border-radius:11px;border:1px solid color-mix(in srgb,CanvasText 20%,transparent);background:Canvas;color:CanvasText;font:inherit}button{padding:10px 14px;border-radius:999px;border:0;background:CanvasText;color:Canvas;font:inherit;font-weight:800;cursor:pointer}button.secondary{background:transparent;color:CanvasText;border:1px solid color-mix(in srgb,CanvasText 20%,transparent)}button.danger{background:transparent;color:#d33;border:1px solid color-mix(in srgb,#d33 45%,transparent)}.stat{min-width:135px;padding:14px;border:1px solid color-mix(in srgb,CanvasText 11%,transparent);border-radius:15px}.stat strong{display:block;font-size:22px}.list{margin-top:14px}.entry{padding:10px 0;border-top:1px solid color-mix(in srgb,CanvasText 9%,transparent)}.entry:first-child{border-top:0}.meta{font-size:12px;opacity:.6;margin-top:4px}.error{color:#d33}.notice{padding:14px 16px;border-radius:14px;border:1px solid color-mix(in srgb,CanvasText 14%,transparent);margin:14px 0}@media(max-width:680px){.grid{grid-template-columns:1fr}.top{align-items:flex-start}.stat{flex:1 1 130px}}
</style></head><body><main>
<div class="top"><div class="brand">SOL · MERCADO LIBRE</div><nav><a href="/">Inicio</a><a href="/life">Vida</a><a href="/executive">Día a día</a></nav></div>
<h1>Tu negocio dentro de SOL.</h1>
<p class="muted">Ventas, publicaciones y preguntas como fuente operativa. Este conector es de sólo lectura: no cambia stock, precios, publicaciones ni responde compradores.</p>
<section id="app"><p class="muted">Cargando…</p></section>
</main><script>
const app=document.getElementById('app');let me,status,accounts=[];function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}async function api(path,o={}){const r=await fetch(path,{cache:'no-store',...o});let b={};try{b=await r.json()}catch{}return{r,b}}function adult(){return me&&(me.role==='owner'||me.role==='adult')}function money(n,c){try{return new Intl.NumberFormat('es-AR',{style:'currency',currency:c||'ARS',maximumFractionDigits:0}).format(Number(n||0))}catch{return (c||'')+' '+Number(n||0).toLocaleString('es-AR')}}function when(v){if(!v)return '';try{return new Intl.DateTimeFormat('es-AR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
async function load(){const [m,s,a]=await Promise.all([api('/v1/auth/me'),api('/v1/mercadolibre/status'),api('/v1/mercadolibre/accounts')]);if(!m.r.ok){app.innerHTML='<div class="card"><h2>Necesitás iniciar sesión</h2><a href="/">Volver</a></div>';return}me=m.b.member;status=s.b;accounts=a.r.ok?(a.b.accounts||[]):[];render()}
function render(){let html='';const query=new URLSearchParams(location.search);if(query.get('error'))html+='<div class="notice error">'+esc(query.get('error'))+'</div>';if(query.get('connected'))html+='<div class="notice">OAuth completado. La primera sincronización puede estar ejecutándose.</div>';if(!status.configured)html+='<div class="card"><h2>Falta configurar OAuth</h2><p>Mercado Libre exige que la URI de retorno registrada sea <strong>HTTPS</strong>. Configurá APP ID, Client Secret y una URL HTTPS exacta antes de conectar la cuenta.</p><pre>SOL_MERCADOLIBRE_CLIENT_ID=...\nSOL_MERCADOLIBRE_CLIENT_SECRET=...\nSOL_MERCADOLIBRE_REDIRECT_URI=https://.../v1/mercadolibre/callback</pre></div>';if(status.configured&&(me.role!=='child'&&me.role!=='guest'))html+='<div class="card"><h2>Conectar cuenta</h2><form id="add"><div class="grid"><label>Nombre<input name="label" value="Mercado Libre" maxlength="120"></label><label style="display:flex;align-items:end;gap:8px"><input name="shared" type="checkbox" style="width:auto" '+(adult()?'':'disabled')+'> Cuenta compartida del hogar/negocio</label></div><button>Autorizar con Mercado Libre</button><span id="addstatus" class="muted"></span></form></div>';html+=accounts.map(accountCard).join('');if(!accounts.length)html+='<div class="card"><p class="muted">Todavía no hay cuentas de Mercado Libre conectadas.</p></div>';app.innerHTML=html;const add=document.getElementById('add');if(add)add.onsubmit=async e=>{e.preventDefault();const s=document.getElementById('addstatus');s.textContent='Preparando autorización…';const f=new FormData(add);const out=await api('/v1/mercadolibre/accounts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({label:f.get('label'),shared:f.get('shared')==='on'})});if(!out.r.ok){s.className='error';s.textContent=out.b.error||'No se pudo iniciar OAuth';return}location.href=out.b.login.authorizationUrl};accounts.forEach(loadDashboard)}
function accountCard(a){return '<div class="card" id="acc-'+esc(a.id)+'"><div class="row"><div><h2>'+esc(a.label)+'</h2><div class="muted">'+esc(a.nickname||'sincronizando perfil')+(a.siteId?' · '+esc(a.siteId):'')+(a.userId?' · seller '+esc(a.userId):'')+'</div></div><span class="pill">'+esc(a.status)+'</span></div>'+(a.lastError?'<p class="error">'+esc(a.lastError)+'</p>':'')+(a.canManage?'<div class="actions"><button class="secondary sync">Sincronizar ahora</button><button class="secondary reconnect">Reautorizar</button><button class="danger disconnect">Desconectar</button></div>':'')+'<div class="dashboard"><p class="muted">Cargando resumen…</p></div></div>'}
async function loadDashboard(a){const root=document.getElementById('acc-'+a.id),box=root.querySelector('.dashboard');const out=await api('/v1/mercadolibre/accounts/'+a.id+'/dashboard');if(!out.r.ok){box.innerHTML='<p class="error">'+esc(out.b.error||'No se pudo cargar')+'</p>';return}const d=out.b.dashboard,s=d.stats;box.innerHTML='<div class="stats"><div class="stat"><strong>'+esc(s.orders)+'</strong><span class="muted">órdenes cargadas</span></div><div class="stat"><strong>'+esc(money(s.revenue,s.currency))+'</strong><span class="muted">ventas pagadas cargadas</span></div><div class="stat"><strong>'+esc(s.activeItems)+'</strong><span class="muted">publicaciones activas</span></div><div class="stat"><strong>'+esc(s.unansweredQuestions)+'</strong><span class="muted">preguntas sin responder</span></div></div>'+section('Últimas ventas',(d.orders||[]).map(o=>'<div class="entry"><strong>'+esc((o.itemTitles||[]).join(' + ')||'#'+o.id)+'</strong><div>'+esc(money(o.totalAmount,o.currencyId))+' · '+esc(o.status)+'</div><div class="meta">'+esc(when(o.occurredAt))+(o.shippingId?' · envío '+esc(o.shippingId):'')+'</div></div>').join(''))+section('Preguntas recientes',(d.questions||[]).map(q=>'<div class="entry"><strong>'+esc(q.itemId||q.id)+'</strong><div>'+esc(q.text)+'</div><div class="meta">'+esc(q.status)+' · '+esc(when(q.dateCreated))+'</div></div>').join(''))+section('Publicaciones',(d.items||[]).slice(0,25).map(i=>'<div class="entry"><strong>'+esc(i.title)+'</strong><div>'+esc(money(i.price,i.currencyId))+' · '+esc(i.status)+'</div><div class="meta">stock API: '+esc(i.availableQuantity??'—')+' · vendidos: '+esc(i.soldQuantity??'—')+'</div></div>').join(''));if(a.canManage){root.querySelector('.sync').onclick=async()=>{const b=root.querySelector('.sync');b.disabled=true;b.textContent='Sincronizando…';const r=await api('/v1/mercadolibre/accounts/'+a.id+'/sync',{method:'POST'});b.disabled=false;b.textContent='Sincronizar ahora';if(!r.r.ok){alert(r.b.error||'Falló sincronización');return}await load()};root.querySelector('.reconnect').onclick=async()=>{const r=await api('/v1/mercadolibre/accounts/'+a.id+'/connect',{method:'POST'});if(r.r.ok)location.href=r.b.login.authorizationUrl;else alert(r.b.error||'No se pudo reautorizar')};root.querySelector('.disconnect').onclick=async()=>{if(!confirm('¿Desconectar esta cuenta? Los datos ya sincronizados quedan en SOL.'))return;await api('/v1/mercadolibre/accounts/'+a.id+'/disconnect',{method:'POST'});await load()}}}
function section(title,body){return '<h3 style="margin-top:22px">'+esc(title)+'</h3><div class="list">'+(body||'<p class="muted">Sin datos.</p>')+'</div>'}
load();
</script></body></html>`;
}
