import { solPage } from "./shell.js";

export function renderOutputsPage(): string {
  const body = `<section class="page">
    <div class="toolbar"><div><div class="eyebrow">SOL · Acciones</div><h1>Lo que SOL puede hacer.</h1><p class="lead">Las acciones externas pertenecen a plugins. SOL concentra permisos, confirmaciones y acceso MCP sin volver a implementar WhatsApp, Calendar, Home Assistant u otros proveedores dentro de Core.</p></div><div class="cluster"><a class="button" href="/mcp">Configurar MCP</a><a class="button primary" href="/services">Administrar servicios</a></div></div>
    <div id="summary" class="grid" style="margin-bottom:16px"><div class="card span4"><div class="stat">—</div><div class="label">plugins con acciones</div></div><div class="card span4"><div class="stat">—</div><div class="label">activos</div></div><div class="card span4"><div class="stat">—</div><div class="label">capacidades</div></div></div>
    <div class="notice" style="margin-bottom:16px"><strong>Separación de permisos.</strong> Leer datos no autoriza una acción. Las tools externas requieren un token MCP con scope <code>external_action</code> y conservan las confirmaciones definidas por cada plugin.</div>
    <section id="outputs"><div class="empty">Cargando acciones…</div></section>
  </section>`;

  const script = `
const root=document.getElementById('outputs'),summary=document.getElementById('summary');
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
async function api(path,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(path,{cache:'no-store',...o,signal:c.signal});let b={};try{b=await r.json()}catch{}if(r.status===401){location.href='/';return{r,b}}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(t)}}
function badge(p){const running=p.state==='running',cls=running?(p.health==='unhealthy'?'bad':p.health==='degraded'?'warn':'good'):p.state==='starting'?'warn':p.state==='error'?'bad':'';return '<span class="badge"><span class="dot '+cls+'"></span>'+esc(running?(p.health==='unknown'?'ejecutando':p.health):p.state)+'</span>'}
function actionsOf(p){return (p.manifest?.capabilities||[]).filter(x=>String(x).startsWith('output.')||String(x).startsWith('tool.'))}
function card(p){const a=actionsOf(p),m=p.manifest;return '<article class="card" style="margin-bottom:12px"><div class="row between"><div><div class="eyebrow">'+esc(m.id)+' · v'+esc(m.version)+'</div><h2 style="margin-top:5px">'+esc(m.name)+'</h2><div class="small muted" style="margin-top:6px">'+esc(m.description||'Plugin de SOL')+'</div></div>'+badge(p)+'</div><div class="divider"></div><div class="label">Capacidades de acción</div><div class="cluster" style="margin-top:7px">'+a.map(x=>'<span class="badge">'+esc(x)+'</span>').join('')+'</div><div class="small muted" style="margin-top:12px">'+(p.state==='running'?'Las tools registradas por este plugin pueden aparecer dinámicamente en SOL MCP.':'Iniciá el plugin desde Servicios para que registre sus tools y capacidades.')+'</div><div class="cluster" style="margin-top:14px"><a class="button" href="/services">Abrir servicio</a><a class="button" href="/mcp">Acceso MCP</a></div></article>'}
async function load(){const [plugins,mcp]=await Promise.all([api('/v1/inputs/plugins'),api('/v1/mcp/status')]);if(!plugins.r.ok){root.innerHTML='<div class="empty error">'+esc(plugins.b.error||'No se pudieron cargar los plugins')+'</div>';return}const all=plugins.b.plugins||[],withActions=all.filter(p=>actionsOf(p).length),active=withActions.filter(p=>p.state==='running').length,count=withActions.reduce((n,p)=>n+actionsOf(p).length,0);summary.innerHTML='<div class="card span4"><div class="stat">'+withActions.length+'</div><div class="label">plugins con acciones</div></div><div class="card span4"><div class="stat">'+active+'/'+withActions.length+'</div><div class="label">activos</div></div><div class="card span4"><div class="stat">'+count+'</div><div class="label">capacidades declaradas</div></div>';root.innerHTML=withActions.length?withActions.map(card).join(''):'<div class="empty">Todavía no hay plugins con capacidades de acción. <a href="/services">Instalá un servicio</a> o revisá sus permisos.</div>';if(!mcp.r.ok)root.insertAdjacentHTML('afterbegin','<div class="notice" style="margin-bottom:12px">No pude consultar el estado MCP: '+esc(mcp.b.error||'desconocido')+'</div>')}
load();setInterval(()=>{if(!document.hidden)load().catch(()=>{})},15000);
`;
  return solPage("outputs", "Acciones", body, script);
}
