import { solPage } from "./shell.js";

export function renderPluginsPage(): string {
  const body = `<section class="page">
    <div class="toolbar">
      <div>
        <div class="eyebrow">SOL · Servicios</div>
        <h1>Plugins.</h1>
        <p class="lead">Instalá, autorizá y administrá módulos de SOL desde un solo lugar. Los procesos de los plugins quedan ocultos y supervisados por SOL.</p>
      </div>
      <div class="cluster"><input id="package" type="file" accept=".solplugin,application/zip" hidden><button class="primary" id="add-plugin">+ Agregar plugin</button></div>
    </div>
    <div class="card soft small" style="margin-bottom:16px"><strong>Instalación segura por repo.</strong> SOL lee el manifest antes de instalar, te muestra los permisos solicitados y descarga únicamente un <code>.solplugin</code> publicado como GitHub Release. Los permisos son autorizaciones del host SOL; todavía no constituyen un sandbox del sistema operativo.</div>
    <div id="summary" class="grid" style="margin-bottom:16px"></div>
    <section id="plugins"><div class="empty">Cargando servicios…</div></section>

    <dialog id="add-dialog"><div class="dialogbody" style="min-width:min(720px,85vw)"><div class="dialoghead"><div><div class="eyebrow">Agregar servicio</div><h2>Instalar plugin</h2></div><button id="add-close">✕</button></div>
      <div class="grid">
        <div class="card span6"><div class="eyebrow">Archivo local</div><h3>.solplugin</h3><p class="muted small">Para paquetes que ya descargaste y en los que confiás.</p><button id="choose-file">Elegir archivo…</button></div>
        <div class="card span6"><div class="eyebrow">Repositorio</div><h3>GitHub</h3><p class="muted small">Pegá <code>owner/repo</code> o la URL del repositorio.</p><input id="repo" style="width:100%" placeholder="diegocesaretti/Codex-audio-remote"><button class="primary" id="repo-preview" style="margin-top:10px">Revisar plugin</button></div>
      </div>
      <div id="repo-result" style="margin-top:14px"></div>
    </div></dialog>

    <dialog id="settings-dialog"><div class="dialogbody" style="min-width:min(680px,85vw)"><div class="dialoghead"><div><div class="eyebrow">Configuración del plugin</div><h2 id="settings-title">Configurar</h2></div><button id="settings-close">✕</button></div><form id="settings-form"></form><div class="cluster" style="justify-content:flex-end;margin-top:16px"><button id="settings-cancel" type="button">Cancelar</button><button id="settings-save" class="primary" type="button">Guardar y aplicar</button></div></div></dialog>

    <dialog id="logs-dialog"><div class="dialogbody"><div class="dialoghead"><div><div class="eyebrow">Plugin logs</div><h2 id="logs-title">Logs</h2></div><button id="logs-close">✕</button></div><pre id="logs" style="white-space:pre-wrap;max-height:60vh;overflow:auto;background:#0d1015;border:1px solid var(--line);border-radius:12px;padding:14px"></pre></div></dialog>
  </section>`;

  const script = `
const API='/v1/inputs/plugins';
const root=document.getElementById('plugins'),summary=document.getElementById('summary'),pick=document.getElementById('package'),addBtn=document.getElementById('add-plugin'),addDlg=document.getElementById('add-dialog'),repo=document.getElementById('repo'),repoResult=document.getElementById('repo-result'),settingsDlg=document.getElementById('settings-dialog'),settingsForm=document.getElementById('settings-form'),logsDlg=document.getElementById('logs-dialog'),logs=document.getElementById('logs');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
async function api(path,o={}){try{const r=await fetch(path,{cache:'no-store',...o});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.message||'Error de conexión'}}}}
function badge(p){const cls=p.state==='running'?(p.health==='unhealthy'?'bad':p.health==='degraded'?'warn':'good'):p.state==='starting'?'warn':p.state==='error'?'bad':'';const label=p.state==='running'?(p.health==='unknown'?'ejecutando':p.health):p.state;return '<span class="badge"><span class="dot '+cls+'"></span>'+esc(label)+'</span>'}
function tokens(items){return (items||[]).length?items.map(x=>'<span class="badge">'+esc(x)+'</span>').join(' '):'<span class="muted small">ninguno</span>'}
function sourceText(p){if(p.source?.type==='github')return 'GitHub · '+esc(p.source.repository||'')+(p.source.releaseTag?' · '+esc(p.source.releaseTag):'');if(p.source?.type==='file')return 'Archivo .solplugin';return 'Instalación anterior'}
function card(p,canManage){const m=p.manifest,run=p.state==='running'||p.state==='starting',hasSettings=(m.settings||[]).length>0;return '<article class="card" style="margin-bottom:12px"><div class="row between"><div><div class="eyebrow">'+esc(m.id)+' · v'+esc(m.version)+'</div><h2 style="margin-top:5px">'+esc(m.name)+'</h2><p class="muted" style="margin:7px 0 0">'+esc(m.description||'Plugin de SOL')+'</p></div>'+badge(p)+'</div><div class="grid" style="margin-top:16px"><div class="span4"><div class="label">Runtime</div><div style="margin-top:5px"><strong>'+esc(m.runtime)+'</strong></div></div><div class="span4"><div class="label">PID</div><div style="margin-top:5px"><strong>'+esc(p.pid||'—')+'</strong></div></div><div class="span4"><div class="label">Origen</div><div class="small" style="margin-top:5px"><strong>'+sourceText(p)+'</strong></div></div></div><div class="divider"></div><div class="small"><div class="label">Capabilities</div><div class="cluster" style="margin-top:6px">'+tokens(m.capabilities)+'</div><div class="label" style="margin-top:12px">Permisos autorizados</div><div class="cluster" style="margin-top:6px">'+tokens(p.approvedPermissions)+'</div></div>'+(p.lastError?'<div class="card soft error small" style="margin-top:14px">'+esc(p.lastError)+'</div>':'')+(canManage?'<div class="cluster" style="margin-top:16px">'+(run?'<button data-action="stop" data-id="'+esc(m.id)+'">Detener</button>':'<button class="primary" data-action="start" data-id="'+esc(m.id)+'">Iniciar</button>')+'<button data-action="restart" data-id="'+esc(m.id)+'">Reiniciar</button>'+(hasSettings?'<button data-config="'+esc(m.id)+'" data-name="'+esc(m.name)+'">Configurar</button>':'')+'<button data-logs="'+esc(m.id)+'">Logs</button><button class="danger" data-remove="'+esc(m.id)+'">Desinstalar</button></div>':'')+'</article>'}
let canManage=false,currentSettingsId='';
async function load(){const out=await api(API);if(!out.r.ok){root.innerHTML='<div class="empty error">'+esc(out.b.error||'No se pudieron cargar los plugins')+'</div>';return}const list=out.b.plugins||[];canManage=!!out.b.canManage;addBtn.style.display=canManage?'':'none';const running=list.filter(x=>x.state==='running').length,healthy=list.filter(x=>x.health==='healthy').length;summary.innerHTML='<div class="card span4"><div class="stat">'+list.length+'</div><div class="label">plugins instalados</div></div><div class="card span4"><div class="stat">'+running+'</div><div class="label">ejecutándose</div></div><div class="card span4"><div class="stat">'+healthy+'</div><div class="label">saludables</div></div>';root.innerHTML=list.length?list.map(x=>card(x,canManage)).join(''):'<div class="empty">No hay plugins instalados todavía.</div>';bind()}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.id,b.dataset.action));document.querySelectorAll('[data-logs]').forEach(b=>b.onclick=()=>showLogs(b.dataset.logs));document.querySelectorAll('[data-config]').forEach(b=>b.onclick=()=>showSettings(b.dataset.config,b.dataset.name));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removePlugin(b.dataset.remove))}
async function action(id,actionName){const out=await api(API+'/'+encodeURIComponent(id)+'/'+actionName,{method:'POST'});if(!out.r.ok)alert(out.b.error||'No se pudo actualizar el plugin');await load()}
async function removePlugin(id){if(!confirm('¿Desinstalar '+id+'? Se eliminarán los archivos del plugin y su configuración local en SOL.'))return;const out=await api(API+'/'+encodeURIComponent(id),{method:'DELETE'});if(!out.r.ok)alert(out.b.error||'No se pudo desinstalar');await load()}
async function showLogs(id){document.getElementById('logs-title').textContent=id;logs.textContent='Cargando…';logsDlg.showModal();const out=await api(API+'/'+encodeURIComponent(id)+'/logs?limit=300');logs.textContent=out.r.ok?(out.b.logs||[]).map(x=>'['+x.at+'] '+x.level.toUpperCase()+' '+x.stream+' · '+x.message).join('\\n'):(out.b.error||'Error')}
function settingField(d,value){const id='setting-'+d.key,desc=d.description?'<div class="muted small" style="margin-top:4px">'+esc(d.description)+'</div>':'';if(d.type==='boolean')return '<label class="card soft" style="display:block;margin-bottom:10px"><input id="'+id+'" data-setting="'+esc(d.key)+'" data-type="boolean" type="checkbox" '+(value===true?'checked':'')+'> <strong>'+esc(d.label)+'</strong>'+desc+'</label>';if(d.type==='select')return '<label style="display:block;margin-bottom:12px"><div class="label">'+esc(d.label)+'</div><select id="'+id+'" data-setting="'+esc(d.key)+'" data-type="select" style="width:100%;margin-top:5px">'+(d.options||[]).map(o=>'<option value="'+esc(o.value)+'" '+(String(value??'')===String(o.value)?'selected':'')+'>'+esc(o.label)+'</option>').join('')+'</select>'+desc+'</label>';const inputType=d.type==='number'?'number':d.type==='secret'?'password':'text';const attrs=d.type==='number'?' min="'+esc(d.min??'')+'" max="'+esc(d.max??'')+'"':'';return '<label style="display:block;margin-bottom:12px"><div class="label">'+esc(d.label)+'</div><input id="'+id+'" data-setting="'+esc(d.key)+'" data-type="'+esc(d.type)+'" type="'+inputType+'" value="'+esc(value??'')+'" '+attrs+' style="width:100%;margin-top:5px" placeholder="'+(d.type==='path'?'Ruta…':'')+'">'+desc+'</label>'}
async function showSettings(id,name){currentSettingsId=id;document.getElementById('settings-title').textContent=name||id;settingsForm.innerHTML='<div class="empty">Cargando…</div>';settingsDlg.showModal();const out=await api(API+'/'+encodeURIComponent(id)+'/settings');if(!out.r.ok){settingsForm.innerHTML='<div class="empty error">'+esc(out.b.error||'Error')+'</div>';return}const defs=out.b.definitions||[],values=out.b.values||{};settingsForm.innerHTML=defs.length?defs.map(d=>settingField(d,values[d.key])).join(''):'<div class="empty">Este plugin no tiene configuración editable.</div>'}
async function saveSettings(){if(!currentSettingsId)return;const values={};settingsForm.querySelectorAll('[data-setting]').forEach(el=>{const key=el.dataset.setting,type=el.dataset.type;if(type==='boolean')values[key]=el.checked;else if(type==='number'&&el.value!=='')values[key]=Number(el.value);else if(el.value!=='')values[key]=el.value});const btn=document.getElementById('settings-save');btn.disabled=true;btn.textContent='Guardando…';const out=await api(API+'/'+encodeURIComponent(currentSettingsId)+'/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({values})});btn.disabled=false;btn.textContent='Guardar y aplicar';if(!out.r.ok){alert(out.b.error||'No se pudo guardar');return}settingsDlg.close();await load()}
function renderRepoPreview(p){const m=p.manifest,perms=m.permissions||[];return '<div class="card"><div class="row between"><div><div class="eyebrow">'+esc(p.repository)+' · '+esc(p.defaultBranch)+'</div><h3>'+esc(m.name)+' · v'+esc(m.version)+'</h3><p class="muted small">'+esc(m.description||'Plugin de SOL')+'</p></div><span class="badge">'+(p.private?'privado':'público')+'</span></div><div class="divider"></div><div class="label">Capabilities</div><div class="cluster" style="margin-top:6px">'+tokens(m.capabilities)+'</div><div class="label" style="margin-top:12px">Permisos que solicita</div><div class="cluster" style="margin-top:6px">'+tokens(perms)+'</div>'+(perms.length?'<label class="card soft small" style="display:block;margin-top:14px"><input id="repo-consent" type="checkbox"> Autorizo a este plugin a usar dentro de SOL los permisos indicados arriba.</label>':'<div class="muted small" style="margin-top:12px">Este plugin no solicita permisos del host.</div>')+'<div class="cluster" style="justify-content:flex-end;margin-top:14px"><button class="primary" id="repo-install">Autorizar e instalar</button></div></div>'}
let repoPreviewData=null;
async function previewRepo(){const value=repo.value.trim();if(!value)return;repoResult.innerHTML='<div class="empty">Revisando repositorio…</div>';const out=await api(API+'/github/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repository:value})});if(!out.r.ok){repoPreviewData=null;repoResult.innerHTML='<div class="card soft error small">'+esc(out.b.error||'No se pudo leer el repositorio')+(out.b.githubAuthRequired?' · Configurá SOL_GITHUB_TOKEN para repos privados.':'')+'</div>';return}repoPreviewData=out.b.preview;repoResult.innerHTML=renderRepoPreview(repoPreviewData);document.getElementById('repo-install').onclick=installRepo}
async function installRepo(){if(!repoPreviewData)return;const perms=repoPreviewData.manifest.permissions||[],consent=document.getElementById('repo-consent');if(perms.length&&!consent?.checked){alert('Tenés que autorizar los permisos solicitados antes de instalar.');return}const btn=document.getElementById('repo-install');btn.disabled=true;btn.textContent='Instalando…';const out=await api(API+'/github/install',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({repository:repo.value.trim(),approvedPermissions:perms})});btn.disabled=false;btn.textContent='Autorizar e instalar';if(!out.r.ok){alert(out.b.error||'No se pudo instalar');return}addDlg.close();repoResult.innerHTML='';repo.value='';repoPreviewData=null;await load()}
addBtn.onclick=()=>{repoResult.innerHTML='';repoPreviewData=null;addDlg.showModal()};document.getElementById('add-close').onclick=()=>addDlg.close();document.getElementById('choose-file').onclick=()=>pick.click();document.getElementById('repo-preview').onclick=previewRepo;repo.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();previewRepo()}};
pick.onchange=async()=>{const file=pick.files?.[0];if(!file)return;if(!file.name.toLowerCase().endsWith('.solplugin')){alert('Seleccioná un archivo .solplugin');pick.value='';return}const out=await api(API+'/install',{method:'POST',headers:{'content-type':'application/octet-stream','x-sol-plugin-filename':file.name},body:file});pick.value='';if(!out.r.ok){alert(out.b.error||'No se pudo instalar');return}addDlg.close();await load()};
document.getElementById('settings-close').onclick=()=>settingsDlg.close();document.getElementById('settings-cancel').onclick=()=>settingsDlg.close();document.getElementById('settings-save').onclick=saveSettings;document.getElementById('logs-close').onclick=()=>logsDlg.close();
load();setInterval(()=>{if(!document.hidden)load()},5000);
`;
  return solPage("plugins", "Servicios", body, script);
}
