import { solPage } from "./shell.js";

export function renderSettingsPage(): string {
  const body = `<section class="page">
    <div class="eyebrow">SOL · Configuración</div>
    <h1>Configuración y mantenimiento.</h1>
    <p class="lead">Estado local, base de datos y herramientas de recuperación. Los resets están limitados al propietario y requieren una frase explícita.</p>
    <section id="app"><div class="empty">Cargando configuración…</div></section>
  </section>`;

  const script = `
const app=document.getElementById('app');
const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','\"':'&quot;'}[c]));
async function api(path,o={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(path,{cache:'no-store',...o,signal:c.signal});let b={};try{b=await r.json()}catch{}return{r,b}}catch(e){return{r:{ok:false,status:0},b:{error:e?.name==='AbortError'?'Tiempo de espera agotado':e?.message||'Error de conexión'}}}finally{clearTimeout(t)}}
function phraseBox(id,phrase,label,copy){return '<article class="card span6"><div class="eyebrow">'+esc(label)+'</div><h2 style="margin-top:6px">'+esc(copy)+'</h2><p class="muted small" style="line-height:1.55">Escribí <strong>'+esc(phrase)+'</strong> para habilitar esta operación.</p><input id="'+id+'-confirm" autocomplete="off" placeholder="'+esc(phrase)+'"><button class="danger" id="'+id+'" style="margin-top:12px">'+esc(copy)+'</button><div class="small muted" id="'+id+'-status" style="margin-top:8px"></div></article>'}
async function runReset(mode,phrase,id){const input=document.getElementById(id+'-confirm'),button=document.getElementById(id),status=document.getElementById(id+'-status');if(input.value.trim()!==phrase){status.className='small error';status.textContent='La frase no coincide.';return}if(!confirm(mode==='factory'?'Esto borra los datos de SOL, plugins, sesiones/configuración local y vuelve al asistente inicial. ¿Continuar?':'Esto borra los datos de SOL en Neon y vuelve al onboarding. La URL de Neon y los plugins locales se conservan. ¿Continuar?'))return;button.disabled=true;status.className='small warntext';status.textContent='Ejecutando reset…';const out=await api('/v1/admin/reset',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode,confirmation:phrase})});if(!out.r.ok){button.disabled=false;status.className='small error';status.textContent=out.b.error||'No se pudo ejecutar el reset';return}status.className='small goodtext';status.textContent='Reset aceptado. SOL se reiniciará automáticamente.';setTimeout(()=>location.href='/',1200)}
async function load(){const [me,sys]=await Promise.all([api('/v1/auth/me'),api('/v1/admin/system')]);if(!me.r.ok){location.href='/';return}if(!sys.r.ok){app.innerHTML='<div class="empty error">'+esc(sys.r.status===403?'Sólo el propietario puede abrir las herramientas de mantenimiento.':sys.b.error||'No se pudo cargar')+'</div>';return}const d=sys.b.database||{};app.innerHTML='<div class="grid"><article class="card span12"><div class="row between"><div><h2>Base Neon</h2><div class="small muted" style="margin-top:5px">Se muestra sólo host y nombre; usuario y contraseña nunca se exponen en la UI.</div></div><span class="badge"><span class="dot good"></span>configurada</span></div><div class="grid" style="margin-top:14px"><div class="span6"><div class="label">Host</div><strong>'+esc(d.host||'—')+'</strong></div><div class="span6"><div class="label">Database</div><strong>'+esc(d.database||'—')+'</strong></div></div>'+(sys.b.legacyNexoSchemaPresent?'<div class="notice warntext" style="margin-top:14px">Se detectó el schema legado <code>whatsapp_nexo</code>. El reset completo lo elimina.</div>':'')+'</article>'+phraseBox('reset-db',sys.b.reset.databaseConfirmation,'Datos','Reiniciar base de datos')+phraseBox('reset-factory',sys.b.reset.factoryConfirmation,'Fábrica','Restablecer SOL completo')+'<article class="card span12 soft"><strong>Qué conserva cada opción</strong><div class="divider"></div><div class="grid"><div class="span6"><div class="label">Reiniciar base</div><p class="small muted">Conserva <code>DATABASE_URL</code>, instalación de plugins y sus datos locales. Limpia hogares, usuarios, sesiones, Life, Knowledge, inputs y acciones.</p></div><div class="span6"><div class="label">Restablecer SOL</div><p class="small muted">Además elimina plugins instalados, plugin-data y configuración local, borra el schema legado de Nexo si existe y vuelve a la pantalla para configurar Neon.</p></div></div></article></div>';document.getElementById('reset-db').onclick=()=>runReset('database',sys.b.reset.databaseConfirmation,'reset-db');document.getElementById('reset-factory').onclick=()=>runReset('factory',sys.b.reset.factoryConfirmation,'reset-factory')}
load();
`;
  return solPage("settings", "Configuración", body, script);
}
